### ISSUE TITLE
20-config.mqsc doesn't with ibmcom/mq:9-lts

### ISSUE THREAD

**Issue by stanislasbonifetto** [ibm-messaging/mq-container#118]
I'm tried to use the `9-lts` tag, but it doesn't load a custom configuration file if the name is `20-config.mqsc` like is describe in the usage documentation https://github.com/ibm-messaging/mq-container/blob/master/docs/usage.md

I have look at the entrypoint in the `9-lts` and it looks it loads only file with name `config.mqsc`.
At the end solution is to rename the file from `20-config.mqsc` to `config.mqsc`, but I think should be good update the documentation.

**Comment by arthurbarr** [comment]
This repo doesn't currently support MQ version 9.0.0.  For that, you need to use the older samples from the [mq-docker](https://github.com/ibm-messaging/mq-docker/) repo.
