### ISSUE TITLE
Error pulling image

### ISSUE THREAD

**Issue by billvickery** [ibm-messaging/mq-container#130]
I get the below error:

docker run -e DISPLAY=$(ipconfig getifaddr en0):0 -v /tmp/.X11-unix:/tmp/.X11-unix -u 0 -ti mq-explorer
Unable to find image 'mq-explorer:latest' locally
docker: Error response from daemon: pull access denied for mq-explorer, repository does not exist or may require 'docker login'.
See 'docker run --help'.

Tried docker login then running again, same error.

**Comment by parrobe** [comment]
Hi @billvickery, The mq-explorer image is not available on dockerhub and must be built beforehand. 

Have you followed the instructions in the [incubating/mq-explorer](https://github.com/ibm-messaging/mq-container/tree/master/incubating/mq-explorer) folder to build mq-explorer image before you run it?

**Comment by billvickery** [comment]
Yes.  I didn't pay close attention to the output of that.  Looks like this step failed:

The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive   && apt-get update   && apt-get install -y     libgtk2.0-0     libxtst6' returned a non-zero code: 100

Other errors/warnings:

Ign:43 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Err:15 http://archive.ubuntu.com/ubuntu xenial/universe Sources
  Connection failed [IP: 91.189.88.162 80]
Ign:18 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
Ign:20 http://archive.ubuntu.com/ubuntu xenial/main all Packages
Ign:21 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages
Ign:22 http://archive.ubuntu.com/ubuntu xenial/restricted all Packages
Ign:23 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:24 http://archive.ubuntu.com/ubuntu xenial/universe all Packages
Ign:25 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:26 http://archive.ubuntu.com/ubuntu xenial/multiverse all Packages
Err:27 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources
  Connection failed [IP: 91.189.88.149 80]
Ign:28 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
Ign:29 http://archive.ubuntu.com/ubuntu xenial-updates/main all Packages
Ign:30 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages
Ign:31 http://archive.ubuntu.com/ubuntu xenial-updates/restricted all Packages
Ign:32 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
Ign:33 http://archive.ubuntu.com/ubuntu xenial-updates/universe all Packages
Ign:34 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages
Ign:35 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse all Packages
Err:36 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
  Connection failed [IP: 91.189.88.162 80]
Ign:37 http://archive.ubuntu.com/ubuntu xenial-backports/main all Packages
Ign:38 http://archive.ubuntu.com/ubuntu xenial-backports/restricted amd64 Packages
Ign:39 http://archive.ubuntu.com/ubuntu xenial-backports/restricted all Packages
Ign:40 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
Ign:41 http://archive.ubuntu.com/ubuntu xenial-backports/universe all Packages
Ign:42 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 Packages
Ign:43 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Reading package lists...
W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/universe/source/Sources  Connection failed [IP: 91.189.88.161 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/universe/source/Sources  Connection failed [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/source/Sources  Connection failed [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/binary-amd64/Packages  Connection failed [IP: 91.189.88.162 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by parrobe** [comment]
Glad to hear it is working now. I will close this issue.
