### ISSUE TITLE
Docker Beginners: Documentation doesnt make it clear what to do with a dockerfile

### ISSUE THREAD

**Issue by samgoulden28** [ibm-messaging/mq-container#152]
In the usage documentation it is not clear what a Dockerfile is or what to do with it. Having the example dockerfile is good, but when following the instructions I had no idea where to put that file or what do with it.

**Comment by arthurbarr** [comment]
Although you can use the `Dockerfile` supplied in this repository directly, we recommend that you build images using the [supplied build instructions](https://github.com/ibm-messaging/mq-container/blob/master/docs/building.md), which use `make` to coordinate the build.
