### ISSUE TITLE
Beginner usage: '20-config.mqsc' in the Dockerfile file is ambiguous and unclear.

### ISSUE THREAD

**Issue by samgoulden28** [ibm-messaging/mq-container#153]
I included the dockerfile exactly as stated in the usage documentation and created a file named 20-config.mqsc in the working directory and got:

COPY failed: stat /var/lib/docker/tmp/docker-builder970108510/20-config.mqsc: no such file or directory

Where does this file need to be saved for this dockerfile to work? It is unclear from the doc.

**Comment by arthurbarr** [comment]
The new `Dockerfile` from the example, and the file `20-config.mqsc` both need to be in the same directory.  I'd also recommend that they're the only files in the directory.  The directory is also know as the Docker build "context", when discussed in the Docker documentation.

**Comment by arthurbarr** [comment]
Fixed by https://github.com/ibm-messaging/mq-container/pull/226
