### ISSUE TITLE
Does this work for building a cluster?

### ISSUE THREAD

**Issue by cra1gl1** [ibm-messaging/mq-container#154]
Wanted to check if this image can be used to build a cluster and if it can, how much additional work does it need.

**Comment by arthurbarr** [comment]
This image just provides an installation of MQ.  You can use that installation of MQ to do whatever MQ can normally do, including MQ clusters.  The work required is to configure MQ, typically with MQSC scripts.  There are [documented instructions](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.0.0/com.ibm.mq.con.doc/q017160_.html) for the non-container case here.  The main difference is that you either need to `docker exec` into the queue manager to simply `runmqsc`, or drop the MQSC files into `/etc/mqm` as discussed in the container's [usage documentation](https://github.com/ibm-messaging/mq-container/blob/master/docs/usage.md)

**Comment by cra1gl1** [comment]
Hi @arthurbarr , dropping mqsc files in /etc/mqm helps with creating cluster objects. But, looks like the docker entrypoint commands, "runmqserver" does't have any code to check if a qmgr is part of the cluster and to "suspend/resume" it before stopping and starting the qmgr, right? 
So, does this needs to be edited to add these features?

**Comment by parrobe** [comment]
you're correct. `runmqserver` does not have any code to check that the queue manager is part of a cluster. It will just create (if it doesn't already exist) and start the queue manager using `strmqm`.

If you want to change the way that the queue manager is started you can fork this repository and make changes to the code to meet your needs.
