### ISSUE TITLE
Issue with LTS container

### ISSUE THREAD

**Issue by StevenCregan** [ibm-messaging/mq-container#156]
After pulling and running the ibmcom/mq:9-lts or /mq:lts container, I'm unable to access the web interface.

I tried on docker for Windows 10, as well as on Ubuntu 16.04.4 LTS

Attempting to use curl on the exposed port resulted in the following:
```
steven@hostname:~$ curl -v -k https://localhost:9443/ibmmq/console

*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.

steven@hostname~$ curl -v -k http://localhost:9443/ibmmq/console

*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9443 (#0)
> GET /ibmmq/console HTTP/1.1
> Host: localhost:9443
> User-Agent: curl/7.47.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

Seems that the internal listener for the container is not receiving to requests passed through the exposed port.

However, the ibmcom/mq:latest container IS functional

**Comment by arthurbarr** [comment]
The web console was introduced in the Continuous Delivery (CD) release of MQ, in V9.0.1.  The current Long Term Support (LTS) release is MQ V9.0.0, so doesn't include the web console.  Part of the split between CD and LTS is that the LTS releases are very stable, and don't receive any new features.  You'll have to use the CD stream (ibmcom/mq:latest) instead, for now.
