### ISSUE TITLE
Error : gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by faissalwise** [ibm-messaging/mq-container#160]
Hello,

I have an error when i run this command :MQ_ARCHIVE=IBM_MQ_9.0.0.0_LINUX_X86-64_TRIAL.tar.gz make build-advancedserver

The output is :

+ false
+ DIR_EXTRACT=/tmp/mq
+ mkdir -p /tmp/mq
+ cd /tmp/mq
+ curl -LO http://build:80/IBM_MQ_9.0.0.0_LINUX_X86-64_TRIAL.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3892  100  3892    0     0   364k      0 --:--:-- --:--:-- --:--:--  380k
+ tar -zxvf ./IBM_MQ_9.0.0.0_LINUX_X86-64_TRIAL.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

The command '/bin/sh -c chmod u+x /usr/local/bin/install-mq.sh   && sleep 1   && install-mq.sh' returned a non-zero code: 2
build-server
build

Thanks for your help.

**Comment by faissalwise** [comment]
Outside the container i can execute tar -zxvf ./IBM_MQ_9.0.0.0_LINUX_X86-64_TRIAL.tar.gz successfully inside downloads directory. So i suspect that the curl -LO http://build:80/IBM_MQ_9.0.0.0_LINUX_X86-64_TRIAL.tar.gz do not download the entire file.

Thanks for your help.

**Comment by cra1gl1** [comment]
I have the exact same issue. Looks like the issue is with the temporarily create network and/or the webserver that's supposed to host the tar.gz.

**Comment by faissalwise** [comment]
Thanks for your response.

**Comment by parrobe** [comment]
Hi @faissalwise,

When we see the error `gzip: stdin: not in gzip format` it means that the curl command has failed to download the archive file from the temporary nginx http server we have started. The most common cause of this is that the archive file in the downloads directory does not have world read permissions on it so the curl command cannot download it. Please check that the permissions for this archive file allow anyone to read it.


On a side note, if i remember correctly the 9 LTS archive you are using does not contain debian installation files but instead contains rpm install files. This will be a problem later on when the install script attempts to install MQ as it will try and do it using apt install which will not work with rpm install files. A possible workaround would be to change the base image from `ubuntu:16.04` to `centos:latest` which will cause the install scripts to use rpm to install instead.

**Comment by faissalwise** [comment]
Hi @parrobe ,
It's resolved,my problem was the proxy in the curl command,so i use curl with noproxy option and that works.

Thanks.

**Comment by patelniks58** [comment]
@faissalwise 
What you have done in local to resolve this issue ?
Other than changing the base image from ubuntu:16.04 to centos:latest 
I am having the same issue still

**Comment by arthurbarr** [comment]
Can you please clarify the name of the tar.go file you are using, and that you've checked it's downloaded correctly (is really a valid file)?
