### ISSUE TITLE
build-advancedserver tries to download software even though it exists in the downloads directory

### ISSUE THREAD

**Issue by cra1gl1** [ibm-messaging/mq-container#162]
# make MQ_VERSION=9.0.5.0 build-advancedserver
Makefile:139: warning: overriding recipe for target 'downloads/mqadv_dev905_linux_x86-64.tar.gz'
Makefile:134: warning: ignoring old recipe for target 'downloads/mqadv_dev905_linux_x86-64.tar.gz'

Downloading IBM MQ Advanced for Developers 9.0.5.0
mkdir -p downloads
cd downloads; curl -LO https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/IBM_MQ_9.0.5.0_LINUX_X86-64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   284  100   284    0     0   1576      0 --:--:-- --:--:-- --:--:--  1577

# make MQ_ARCHIVE=IBM_MQ_9.0.5.0_LINUX_X86-64.tar.gz build-advancedserver
Makefile:139: warning: overriding recipe for target 'downloads/mqadv_dev905_linux_x86-64.tar.gz'
Makefile:134: warning: ignoring old recipe for target 'downloads/mqadv_dev905_linux_x86-64.tar.gz'

Downloading IBM MQ Advanced for Developers 9.0.5.0
mkdir -p downloads
cd downloads; curl -LO https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/IBM_MQ_9.0.5.0_LINUX_X86-64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   284  100   284    0     0    654      0 --:--:-- --:--:-- --:--:--   655

/downloads# ls -lrt
total 879673
-rwxrwxrwx 1 vagrant vagrant 900776791 Jul 12 14:13 IBM_MQ_9.0.5.0_UBUNTU_X86-64.tar.gz
-rwxrwxrwx 1 vagrant vagrant       477 Jul 18 18:12 nohup.out
-rwxrwxrwx 1 vagrant vagrant       284 Jul 18 18:24 IBM_MQ_9.0.5.0_LINUX_X86-64.tar.gz

For some reason it tries to download the "IBM_MQ_9.0.5.0_LINUX_X86-64.tar.gz" and replaces it with some jibberish file.

**Comment by parrobe** [comment]
I'll try and recreate, one thing i have noticed however is that you've set the Archive to be `IBM_MQ_9.0.5.0_LINUX_X86-64.tar.gz` but i can't see that you've changed the `BASE_IMAGE` so it is not using `ubuntu:16.04`.  If you are still using `ubuntu:16.04` the install will fail later when it can't find the debian files to install as the `IBM_MQ_9.0.5.0_LINUX_X86-64.tar.gz` only contains rpm files.

**Comment by parrobe** [comment]
I'm able to reproduce this. Running that command when the files exist causes the mq install file to be overwritten with a 404 HTTP error html file.
