### ISSUE TITLE
mqadvanced-server-dev creates Queue manger name  with lower case

### ISSUE THREAD

**Issue by cra1gl1** [ibm-messaging/mq-container#167]
Wanted to check if this is intentional.

**Comment by arthurbarr** [comment]
Can you be more specific please?  This works fine for me:

```
$ docker run -d --name=test -e LICENSE=accept -e MQ_QMGR_NAME=mixedCase ibmcom/mq
7bca91e424132831425e01ee21bf96f96431785ca36b14c0e74854811af92668
$ docker exec test dspmq
QMNAME(mixedCase)                                         STATUS(Running)
```

**Comment by cra1gl1** [comment]
With “make build-devserver”,  and “docker run —env LICENCE=accept imageid”, I mean when no “MQ_QMGR_NAME” is passed during docker run, it creates a default qmgr as expected, based on the host name. But the created qmgr is in lower case.

**Comment by arthurbarr** [comment]
That also works fine for me:

```
$ docker run -d --name=test2 -e LICENSE=accept --hostname=mixedCase ibmcom/mq
db6d99a9fd5bbb7a35b656a9c78606e58a8093a98cab58e6e3ff44bf68f39c1f
$ docker exec test2 dspmq
QMNAME(mixedCase)                                         STATUS(Running)
```

The queue manager name matches the case of the host name (or the `MQ_QMGR_NAME` environment variable).  This seems like the behaviour I'd expect.  If you want to control the case exactly, then you have to specify it exactly.
