### ISSUE TITLE
should "chkmqhealthy " print out any output ?

### ISSUE THREAD

**Issue by cra1gl1** [ibm-messaging/mq-container#173]
From what i understand, "chkmqhealthy" is used for checking qmgr status, by liveliness probe. so it should return a zero or non-zero exit code. 

But, when I manually run it on the container, it returns some random numbers, trying to understand what that is. I checked the code in "cmd/chkmqhealthy/main.go" and looks like it should print out the combinedoutput (something like this , QMNAME(510AB53DC682)    STATUS(Running)? ). But, what i see is this.

(mq:9.0.5.0)root@510AB53DC682:/# chkmqhealthy
[81 77 78 65 77 69 40 53 49 48 65 66 50 49 68 67 54 65 57 41 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 83 84 65 84 85 83 40 82 85 78 78 73 78 71 41 10]

(mq:9.0.5.0)root@510AB53DC682:/# dspmq
QMNAME(510AB21DC6A9)                                      STATUS(Running)

could you help me understand what this is?

**Comment by arthurbarr** [comment]
This is a bug.  It prints the UTF-8 bytes of the output from `dspmq`.  In your example, it's:

```
QMNAME(510AB21DC6A9)                                      STATUS(RUNNING)
```
The text output is not used, but it's still a bug.
