### ISSUE TITLE
root user: AMQ7077E: You are not authorized to perform the requested operation

### ISSUE THREAD

**Issue by cra1gl1** [ibm-messaging/mq-container#177]
Root user, although member of mqm group can't perform some actions.

vagrant@~$ docker run \
>   --env LICENSE=accept \
>   --env MQ_QMGR_NAME=QM1 \
>   --publish 1414:1414 \
>   --publish 9443:9443 \
>   --detach \
>   ibmcom/mq

(mq:9.1.0.0)root@d563a1e3d493:/# whoami
root
(mq:9.1.0.0)root@d563a1e3d493:/# groups root
root : root mqm
(mq:9.1.0.0)root@d563a1e3d493:/# dspmq
QMNAME(QM1)                                               STATUS(Running)
(mq:9.1.0.0)root@d563a1e3d493:/# endmqm QM1
AMQ7077E: You are not authorized to perform the requested operation.
(mq:9.1.0.0)root@d563a1e3d493:/# dltmqm QM1
AMQ7077E: You are not authorized to perform the requested operation.
(mq:9.1.0.0)root@d563a1e3d493:/# crtmqm QM2
AMQ7077E: You are not authorized to perform the requested operation.
(mq:9.1.0.0)root@d563a1e3d493:/# echo "DEFINE QL(TESTROOT1)" | runmqsc QM1
5724-H72 (C) Copyright IBM Corp. 1994, 2018.
Starting MQSC for queue manager QM1.

     1 : DEFINE QL(TESTROOT1)
AMQ8006I: IBM MQ queue created.
One MQSC command read.
No commands have a syntax error.
All valid MQSC commands were processed.
(mq:9.1.0.0)root@d563a1e3d493:/# dspmqaut -m QM1 -t qmgr -p root
Entity root has the following authorizations for object QM1:
        inq
        set
        connect
        altusr
        crt
        dlt
        chg
        dsp
        setid
        setall
        ctrl
        system
(mq:9.1.0.0)root@d563a1e3d493:/# dspmqaut -m QM1 -t qmgr -p mqm
Entity mqm has the following authorizations for object QM1:
        inq
        set
        connect
        altusr
        crt
        dlt
        chg
        dsp
        setid
        setall
        ctrl
        system
(mq:9.1.0.0)root@d563a1e3d493:/# uname -a
Linux d563a1e3d493 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 x86_64 x86_64 GNU/Linux
(mq:9.1.0.0)root@d563a1e3d493:/# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
(mq:9.1.0.0)root@d563a1e3d493:/#

**Comment by arthurbarr** [comment]
I believe this is just how MQ works.  You can always run those same commands after issuing an `su` to the `mqm` user, or you can use `docker exec --user mqm`.

**Comment by cra1gl1** [comment]
@arthurbarr. In this case, root is a member of mqm group, so it should have all the rights mqm has. And I also noticed that it happens intermittently.

**Comment by cra1gl1** [comment]
I thik this issue should be reopened. 
I see this issue when i run the image on Linux debian-92 4.9.0-4-amd64 host OS, but not when I run it on Linux minikube 4.9.13.

**Comment by parrobe** [comment]
Going to do some side investigation into this before re-opening. Need to check what expected behaviour around group membership is as seeing some interesting results when executing `id`:

```
(mq:9.1.0.0)root@fa8baf8ca092:/# groups
root
(mq:9.1.0.0)root@fa8baf8ca092:/# groups root
root : root mqm
(mq:9.1.0.0)root@fa8baf8ca092:/# id
uid=0(root) gid=0(root) groups=0(root)
(mq:9.1.0.0)root@fa8baf8ca092:/# id root
uid=0(root) gid=0(root) groups=0(root),999(mqm)
```

**Comment by parrobe** [comment]
[This appears to be a common problem in UNIX](https://unix.stackexchange.com/questions/149533/id-command-doesnt-show-all-users-groups). Because we add group membership to root during image build time and because the root user is technically not logged in/out to update this group membership it means that the user root does not have the group membership yet. By running `su` to login me in as the root user i then can see mqm listed in the root users grousp:
```
(mq:9.1.0.0)root@36515b780184:/# id
uid=0(root) gid=0(root) groups=0(root)
(mq:9.1.0.0)root@36515b780184:/# groups
root
(mq:9.1.0.0)root@36515b780184:/# su
(mq:9.1.0.0)root@36515b780184:/# id
uid=0(root) gid=0(root) groups=0(root),999(mqm)
(mq:9.1.0.0)root@36515b780184:/# groups
root mqm
```

**Comment by farazzy4u** [comment]
can this be explained in windows 10 environment ?

**Comment by jcucuzza** [comment]
> If you're getting this error on win10 close out MQ and try starting MQ as administrator.

**Comment by Kumaragurusankar** [comment]
> > If you're getting this error on win10 close out MQ and try starting MQ as administrator.

I have this issue in windows though am running in admin mode

**Comment by anhsaksena** [comment]
We are using Openshift container for MQ. We created a MQ image that has the MQ installation on RHEL. However, we are unable to issue any MQ call (e.g. crtmqm, strmqm) using commands option on the MQ container. Openshift uses/allocates arbitrary user which is a 10-digit number with no username. As such, we couldn't add this arbitrary user to mqm group. Also, the command option on the container doesn't allow su command. Much appreciate if you could advise/suggest a solution for this. Thanks

**Comment by arthurbarr** [comment]
The certified (pre-built) containers don't use RPMs to install MQ, but instead use the new unzippable installer.  This allows us to comply with Red Hat's security guidance on using an arbitrary user, and avoid any switching of users at any time (e.g. `setuid` bits on executables).  So there is no `mqm` user any more, or an `mqm` group.  The `su` command is for switching users, which Red Hat also want to disallow.

The code in this repo, combined with the new unzippable installer, should allow things to work as before, except you no longer have an `mqm` user, and the queue manager will just run as the user which starts it.

**Comment by anhsaksena** [comment]
Unfortunately, we can't use the pre-built container as we have to use company supported RHEL image.

**Comment by arthurbarr** [comment]
The pre-built container is built using the code in this repo.  You just need to be sure to use the new unzippable installer, which can be downloaded from Passport Advantage.

**Comment by arthurbarr** [comment]
Also note that the Red Hat Universal Base Image which we use, is a subset of Red Hat Enterprise Linux and is fully supported if you have a license for RHEL.  See https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image

**Comment by anhsaksena** [comment]
Thanks Arthur, for your advice. It was very helpful! It appears the new unzippable installer is MQ version 9.2. Is that right?

**Comment by anhsaksena** [comment]
Does the equivalent RPM install version of MQ 9.2 provide the same functionality in term of comply with Red Hat's security guidance on using an arbitrary user and hence no need for use of mqm user/group? Or do we have to use the non-install version in order to get that functionality?

**Comment by arthurbarr** [comment]
The new unzippable installer is for MQ 9.2 only.  The RPM installer uses the `mqm` user and group, and also applies the `setuid` bit on most of the executables, so that whichever user you run `strmqm` as, the actual queue manager runs as `mqm`.  So you need to use the unzippable installer to support the use of an arbitrary user ID, for the Red Hat `restricted` SCC.

**Comment by anhsaksena** [comment]
A colleague who has access to Passport Advantage has downloaded 9.2.0.0-IBM-MQ-Advanced-for-Developers-Non-Install-LinuxX64.tar.gz. Is that the unzippable installer you are referring to? Also, it would be great if you could provide the instructions to install it as it seems the installation requires more than using tar to extract the file. Many thanks...

**Comment by anhsaksena** [comment]
Thank you so much Arthur! Used the unzippable installer as per your advises and successfully created and started the queue manager. Have spent days trying to get it working with the RPM installer and got nowhere so you can imagine how happy i'm to see the queue manager created and started. Thanks again.

**Comment by anhsaksena** [comment]
Hi Arthur,

Need help again! I built an MQ container and an IIB container using Openshift. Successfully created a queue manager QM1 and a broker (with -q QM1 option). However, unable to start up the broker, keep getting

BIP6124E: Can not load MQ libraries from Installation Path (''/opt/mqm/lib64/libmqm_r.so'') due to error (''/opt/mqm/lib64/libmqmax_r.so: cannot open shared object file: No such file or directory''). 

Shared opt/mqm from MQ container with the IIB container, even export /opt/mqm/lib64 path but still no luck. So appreciate any advice you can give.

**Comment by anhsaksena** [comment]
Also installed MQ using the unzippable installer on top of IIB image. It appears doing that removes the originally installed IIB from /opt. Is that correct?

**Comment by anhsaksena** [comment]
We have iib version 10.0.0.10 and mq version on the same container. MQ 9.2 was installed using the unzippable installer to support the use of an arbitrary user ID imposed by Openshift. We now have the error below

mqsireportproperties WMBVM1BRK -b webadmin -o server -a
BIP8034E: An internal configuration response message not received. 
This command sends an internal configuration message to the integration node, an internal configuration response message was not received from that integration node. 
Ensure that the integration node is running. 

Is the unzippable version of MQ compatible with IIB 10.0.0.10? Appreciate if you can advise of any possible cause or fix.

**Comment by arthurbarr** [comment]
I'd generally recommend that ACE/IIB should run in a separate container from MQ (though [you can still do server bindings](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.2.0/com.ibm.mq.ctr.doc/q114488_.htm) if you share the right namespaces), but I think there are some limitations when you do this with IIB. @IBMRob might be able to comment on the latest on this.

As an aside, @anhsaksena, it may be worth opening a new issue, as comments on this closed issue could easily get lost.

**Comment by IBMRob** [comment]
Unfortunately we have not been able to perform any more research into running MQ in a different container but same pod to perform server bindings. We have been concentrating on the MQ Client connections as part of our new operator releases.

**Comment by anhsaksena** [comment]
Thanks Arthur and Rob for your advise. We are shelfing this work until IIB is upgraded to v11 as it seems IIB 10 isn't supported on Openshift.
