### ISSUE TITLE
Does this image configures the linux kernal resources required for IBM MQ?

### ISSUE THREAD

**Issue by cra1gl1** [ibm-messaging/mq-container#190]
If it doesn't configure them, is there a way to do it using this image?
https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_7.5.0/com.ibm.mq.ins.doc/q008550_.htm

**Comment by parrobe** [comment]
Hi @cra1gl1 - Need to look into this further but from first glance the link you've posted is a version 7.5 link. You would need to use at least version 8 or above as MQ wasn't supported in a container until then.

 - 9.1 Link - [https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ins.doc/q008550_.htm](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ins.doc/q008550_.htm)
 - 8.0 Link - [https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.ins.doc/q008550_.htm](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.ins.doc/q008550_.htm)

**Comment by arthurbarr** [comment]
Kernel configuration is usually independent of what goes on inside the container image.  Containers isolate lots of things, but use a shared kernel.  The values of the settings are therefore host-dependent.

The settings in the Knowledge Center are really for guidance only when running in containers, and apply to running multiple queue managers in a VM, but it's worth looking into them when you're tuning performance.
