### ISSUE TITLE
Does this image contain the monitor program (mq metrics exporter) for Prometheus?

### ISSUE THREAD

**Issue by cra1gl1** [ibm-messaging/mq-container#194]
I couldn't find the program on the container. Does this image create it? If yes, where is it stored.

**Comment by arthurbarr** [comment]
The HTTP metrics endpoint is integrated into `runmqserver`.  The [`internal/metrics`](https://github.com/ibm-messaging/mq-container/tree/master/internal/metrics) package is invoked from the [`main`](https://github.com/ibm-messaging/mq-container/blob/master/cmd/runmqserver/main.go#L127) function in `runmqserver`
