### ISSUE TITLE
can the runmqserver/runmqdevserver be run as non root user?

### ISSUE THREAD

**Issue by rakesh-4321** [ibm-messaging/mq-container#196]
Looks like some of the container platforms(ex: openshift) doesn't allow processes inside container to be run as root user. And the runmqserver/runmqdevserver in this image is run as root user. Can these processes be switched to a not root user, may be mqm? Would anything break if we do this?

**Comment by arthurbarr** [comment]
This is very much related to [issue 197](https://github.com/ibm-messaging/mq-container/issues/197).  MQ itself can run as non-root, but in some environments, we need the root user to get the right permissions on the persistent volume.  We are working on some improvements which will allow running as non-root, with a separate "init container" to set up the volume permissions (which could be run as root or non-root, depending on your storage).
