### ISSUE TITLE
endmqm QM1 ==> container exits too, why ???

### ISSUE THREAD

**Issue by FatihaBiga** [ibm-messaging/mq-container#210]
hi everyone,
i have an issue which is i do an endmqm to my queue inside the container and it exits immedialty
it happens in both version 8 and 9 images.
 i still want to work iside my container , even my QM is down i need to know how to delete and avoid this issue.
thank you

**Comment by arthurbarr** [comment]
There's nothing in the latest containers which should do this.  If you are using an old image, built from the [deprecated code base](https://github.com/ibm-messaging/mq-docker), then there is a health check which will end the container if the queue manager fails.  You should look at the [mq-monitor-qmgr.sh](https://github.com/ibm-messaging/mq-docker/blob/master/mq-monitor-qmgr.sh) script in that repository.

Alternatively, if you are using Kubernetes using the IBM supplied Helm charts, you will have a liveness probe running, which will be checking the health of the queue manager for you.

I'd be interested to know why you want to run a container after a queue manager is stopped though.  Most use cases can be managed in other ways, but let us know if there's something specific you can't do.

**Comment by FatihaBiga** [comment]
this is the project i dwonload ([https://github.com/ibm-messaging/mq-docker/tree/mq-8) ](url)
then i run a container with : docker run \
  --env LICENSE=accept \
  --env MQ_QMGR_NAME=QM1 \
  --publish 1414:1414 \
  -d mq8:base 
then like i said i do an endmqm inside the container the the mq and container stops both of them ?

**Comment by arthurbarr** [comment]
This is the wrong repository for that code.  You have raised the issue in "ibm-messaging/mq-container" instead of "ibm-messaging/mq-docker".
