### ISSUE TITLE
How to build a RHEL image with the 9.0.5-dev branch?

### ISSUE THREAD

**Issue by cra1gl1** [ibm-messaging/mq-container#242]
Looks like only the master repo has a separate makefile-rhel to build a rhel image. Is there a way to build it with the 9.0.5-dev repo?

**Comment by arthurbarr** [comment]
There aren't a lot of functional differences between MQ V9.0.5 and MQ V9.1, so you could probably build an image using the `9.1.0-sep` branch, but using a `tar.gz` file for MQ V9.0.5.

Note, however, that MQ V9.0.5 will go out of support when the next MQ Continuous Delivery release becomes available (usually every four months or so, and the last one was in July 2018).
