### ISSUE TITLE
Websphere MQ Resource Adapter is not delivering messages with a body length 0

### ISSUE THREAD

**Issue by mvanholsteijn** [ibm-messaging/mq-container#255]
Hi,

We observed that the Websphere MQ Resource Adapter for JEE is not delivering messages with body length 0. When it receives one it gives the message: `JMSCC0108:IBM MQ classes for JMS had detected a message, ready for asynchronous delivery to an application. When delivery was attempted, the message was no longer available`

It hurts us as we are expecting arrival confirmations, which have no body.

Do you know why this is?

**Comment by parrobe** [comment]
Hi @mvanholsteijn, This GitHub repo is for raising issues specifically against the IBM MQ Container image. I'm afraid we don't know the answer to that question as it appears to be about WebSphere MQ Resource adapters.

I would suggest that either you open a PMR with the MQ Support team or alternatively you could post the same question on any of the following forums:

[MQ Mailing List](https://listserv.meduniwien.ac.at/cgi-bin/wa?A0=MQSERIES)
[MQ Forum](http://www.mqseries.net/phpBB2/index.php?sid=f77ea1fa1728db3465acb0fb6ce15285)
[StackOverflow](https://stackoverflow.com/questions/tagged/ibm-mq)

**Comment by mvanholsteijn** [comment]
Thank you! Sorry for bothering you with this question.
