### ISSUE TITLE
MQ container with SDK and GO package

### ISSUE THREAD

**Issue by murtuzamatiwala** [ibm-messaging/mq-container#257]
Hello,

Please can you help me with how to build an MQ container having the ibmmq-sdk package installed and if possible even the golang package.

Thanks !

**Comment by arthurbarr** [comment]
There's a sample for building a [mq-golang-sdk](https://github.com/ibm-messaging/mq-container/tree/master/incubating/mq-golang-sdk) image.  This image is a layer on top of the [mq-sdk](https://github.com/ibm-messaging/mq-container/tree/master/incubating/mq-sdk) image.

These samples use the MQ Advanced for Developers installation package, and just install the SDK bits.  Note that in MQ V9.1.1, the redistributable clients (download from [here](https://developer.ibm.com/messaging/mq-downloads/)) also include the SDK, so may be an easier way to go, if you want to download fewer files.
