### ISSUE TITLE
Creating multiple Docker Images including one as <none>:<none>

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/mq-container#262]
Hello All,

I used the scripts to prepare a MQ Docker Image on Ubuntu Server. I noticed that when the script is done with execution, I have 4 images created on my server with one image tagged as <none>:<none>

mqadvanced-server   9.1.1.0-x86_64-ubuntu-16.04   1f7a7bff0f44        15 seconds ago       616MB

none              none                        d1b83e5bc623        About a minute ago   669MB

mq-golang-sdk       9.1.1.0-x86_64-ubuntu-16.04   d3931b3e3a23        2 minutes ago        629MB

mq-sdk              9.1.1.0-x86_64-ubuntu-16.04   47af3e778845        2 minutes ago        380MB

I am not sure what the this none:none image. ?
Also, is this the final MQ Docker Image which can be used - mqadvanced-server:9.1.1.0-x86_64-ubuntu-16.04 ?

DOCKER INFO : 
-----------------------
ubuntu@ip-172-31-90-84:~/UP/mq-container-master$ sudo docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
ubuntu@ip-172-31-90-84:~/UP/mq-container-master$

UBUNTU VERSION
----------------------------------
ubuntu@ip-172-31-90-84:~/UP/mq-container-master$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
ubuntu@ip-172-31-90-84:~/UP/mq-container-master$

**Comment by parrobe** [comment]
hiya,

Yes the final MQ image you can use to run IBM MQ in a container is `mqadvanced-server:9.1.1.0-x86_64-ubuntu-16.04`.

The `mq-sdk 9.1.1.0-x86_64-ubuntu-16.04` image is the MQ SDK in a container

The `mq-golang-sdk 9.1.1.0-x86_64-ubuntu-16.04` is the MQ SDK and the golang SDK in a container.

Both the mq-sdk and mq-golang-sdk are created and used during the build process to create the final image.

I'm unsure what the <none>:<none> image is and will look into this

**Comment by SAshish19** [comment]
Thanks Rob for the confirmation. As specified it would help if you can share your findings regarding the none:none image.

Also, I can't use these scripts for upgrading(applying fix patches) the MQ Docker Image created. (For reasons like the script would try to accept the license but the Fix Patch installer would have no such license file OR the installation of the Fix Patch rpm packages would fail since the base version rpm packagaes would not be available) . In such case , do we have any GitHUB script that would upgrade an existing MQ Docker Image created using these scripts ?

Regards

**Comment by SAshish19** [comment]
Hello,

Any thoughts on upgrading process requested above would be helpful.

Thanks

**Comment by arthurbarr** [comment]
Closing this issue as I think it's resolved.  The upgrade issue is considered an enhancement, and is being tracked in #305
