### ISSUE TITLE
pull access denied for mq-sdk, repository does not exist or may require 'docker login' error

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/mq-container#265]
Hello,

I am getting the error : pull access denied for mq-sdk, repository does not exist or may require 'docker login' with MQv9.1.0.0 LTS release downloaded from : https://developer.ibm.com/messaging/mq-downloads/

The installer has *.deb files. I am using below Docker version on Ubuntu 16.04 :

Client:
Version: 18.09.1
API version: 1.39
Go version: go1.10.6
Git commit: 4c52b90
Built: Wed Jan 9 19:35:23 2019
OS/Arch: linux/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.1
API version: 1.39 (minimum version 1.12)
Go version: go1.10.6
Git commit: 4c52b90
Built: Wed Jan 9 19:02:44 2019
OS/Arch: linux/amd64
Experimental: false

ERROR :
148 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

false
DIR_EXTRACT=/tmp/mq
mkdir -p /tmp/mq
cd /tmp/mq
curl -LO http://build:80/mqadv_dev910_ubuntu_x86-64.tar.gz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 153 100 153 0 0 68000 0 --:--:-- --:--:-- --:--:-- 76500
tar -zxvf ./mqadv_dev910_ubuntu_x86-64.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c chmod u+x /usr/local/bin/install-mq.sh && sleep 1 && install-mq.sh && rm -rf /var/mqm && /opt/mqm/bin/crtmqdir -f -s' returned a non-zero code: 2
build-server
build
docker build --build-arg BASE_IMAGE=mq-sdk:9.1.0.0-x86_64-ubuntu-16.04 -t mq-golang-sdk:9.1.0.0-x86_64-ubuntu-16.04 -f incubating/mq-golang-sdk/Dockerfile .
Sending build context to Docker daemon 10.85MB
Step 1/7 : ARG BASE_IMAGE=mq-sdk:9.0.5.0-x86_64-ubuntu-16.04
Step 2/7 : FROM $BASE_IMAGE
pull access denied for mq-sdk, repository does not exist or may require 'docker login'
Makefile:283: recipe for target 'build-golang-sdk-ex' failed
make: *** [build-golang-sdk-ex] Error 1

**Comment by SAshish19** [comment]
I was able to resolve it. Closing

**Comment by caic** [comment]
Hi, 

I'm getting the same error.

How did you resolve it?

Thank you!

**Comment by SAshish19** [comment]
Hi,

Its been long time but if i recollect correctly I executed the image creation command with "root" before giving 775 permissions to the directory and files within.

Regards

**Comment by caic** [comment]
Hi,

I've checked perms and I'm execute the make command with root but I keep getting the same error:

```
(...)
Installed:
  bc.x86_64 0:1.06.95-13.el7              file.x86_64 0:5.11-35.el7

Updated:
  glibc-common.x86_64 0:2.17-260.el7_6.6  util-linux.x86_64 0:2.23.2-59.el7_6.1

Dependency Updated:
  glibc.x86_64 0:2.17-260.el7_6.6      libblkid.x86_64 0:2.23.2-59.el7_6.1
  libmount.x86_64 0:2.23.2-59.el7_6.1  libsmartcols.x86_64 0:2.23.2-59.el7_6.1
  libuuid.x86_64 0:2.23.2-59.el7_6.1

Complete!
+ DIR_EXTRACT=/tmp/mq
+ mkdir -p /tmp/mq
+ cd /tmp/mq
+ curl -LO http://build:80/IBM_MQ_9.1.0.0_LINUX_X86-64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   284  100   284    0     0   1400      0 --:--:-- --:--:-- --:--:--  1405
+ tar -zxvf ./IBM_MQ_9.1.0.0_LINUX_X86-64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c chmod u+x /usr/local/bin/install-mq.sh   && sleep 1   && install-mq.sh   && rm -rf /var/mqm   && /opt/mqm/bin/crtmqdir -f -s' returned a non-zero code: 2
build-server
build
docker build --build-arg BASE_IMAGE=mq-sdk:9.1.0.0-x86_64-centos-7 -t mq-golang-sdk:9.1.0.0-x86_64-centos-7 -f incubating/mq-golang-sdk/Dockerfile .
Sending build context to Docker daemon  1.581GB
Step 1/7 : ARG BASE_IMAGE=mq-sdk:9.0.5.0-x86_64-ubuntu-16.04
Step 2/7 : FROM $BASE_IMAGE
pull access denied for mq-sdk, repository does not exist or may require 'docker login'
make: *** [build-golang-sdk] Error 1
[root@docker-01 v9.1.0]# 
```

I realized after a faild execution my tar file went to a 404 error:

```
[root@docker-01 v9.1.0]# cat downloads/IBM_MQ_9.1.0.0_LINUX_X86-64.tar.gz
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /ibmdl/export/pub/software/websphere/messaging/mqadv/IBM_MQ_9.1.0.0_LINUX_X86-64.tar.gz was not found on this server.</p>
</body></html>
```

I think the problem is in the curl:

`+ curl -LO http://build:80/IBM_MQ_9.1.0.0_LINUX_X86-64.tar.gz`

But I can not find out exactly what is wrong.

Any idea?

Thank you very much!

**Comment by arthurbarr** [comment]
In the 9.1.0 branch, I think you needed to build the SDK image first using `make build-sdk`.  This process has changed in the newer code branches.

**Comment by caic** [comment]
Hello,

After many attempts and since I was workin in a AWS EC2 instance, I tried it in my Macbook and everything was OK.

Thanks!
