### ISSUE TITLE
Big MQSC scripts are not loaded

### ISSUE THREAD

**Issue by DSTOLF** [ibm-messaging/mq-container#277]
Hi,

I have an MQSC script automatically generated on our production environment that has 5673 lines. I'm trying to port to MQ container, but it simply doesn't load it on startup.

I've managed to reduce it to 245 by removing all commented lines and making all multi-line commands a single line with the shell script bellow:
`cat config.mqsc | grep -v '^*' | sed ':a;N;$!ba;s/+\n/ /g' > 20-config.mqsc`

Still, it doesn't load. But breaking it into smaller, 50 lines files did the trick:
```
cat config.mqsc | grep -v '^*' | sed ':a;N;$!ba;s/+\n/ /g' > temp
split --lines=50 --additional-suffix=.mqsc temp 20-config.
```

Ok, so now all files are correctly loaded on startup. So I debugged a little further and I think I've found where where it all goes wrong.

[`io.Copy`](https://github.com/ibm-messaging/mq-container/blob/2dbee560fe32bed4e9335eacb4cef510273aa3a4/cmd/runmqserver/qmgr.go#L107) seems to be the problem.

I've made a [simplified version](https://gist.github.com/DSTOLF/1de349c95a5bea009b05058f0a3b985f) of the `configureQueureManager` function, so you can test it for yourself.

```
$ < /dev/urandom tr -dc "\t\n [:alnum:]" | head -c10000 > /tmp/tests/20-config.mqsc
$ cat /tmp/tests/20-config.mqsc  | wc -l
168
$ go run testFiles.go
2019/02/20 12:04:17 Running MQSC file  /tmp/tests/20-config.mqsc
2019/02/20 12:04:17 Finished Processing  /tmp/tests/20-config.mqsc
2019/02/20 12:04:17 Output for "runmqsc" with /tmp/tests/20-config.mqsc:


$ < /dev/urandom tr -dc "\t\n [:alnum:]" | head -c1000000 > /tmp/tests/20-config.mqsc
$ cat /tmp/tests/20-config.mqsc  | wc -l
15471
$ go run testFiles.go
2019/02/20 12:04:47 Running MQSC file  /tmp/tests/20-config.mqsc
... (hangs) ...
```

It seems that it's not so much the amount of lines, but the size of the file itself. I'm not so proficient on Go, so I'm not sure if there's a fix for it, some other fuction that could be used or a workaround. For now, we're breaking breaking the script into smaller files in our CI, but it would be nice if we didn't have to do that.

Best regards.

**Comment by parrobe** [comment]
It appears the current upper limit for MQSC files is approximately 64KB. Files bigger than this are likely to fail silently and files bigger than 77KB definitely will.
