### ISSUE TITLE
Customize qm.ini

### ISSUE THREAD

**Issue by smikishk** [ibm-messaging/mq-container#293]
This is more of a question rather than an issue. Read through the documentation, but cannot find an native way to customize mq.ini file.

/var/mqm/qmgrs/\<QMGR\>/qm.ini

We need to customize this file (specifically, concurrent channel connections).  Is there a native MQ command similar to MQ Appliance' setmqini to issue adds/updates/deletes to the stanzas?

If not, would I have to parse this file line by line and regenerate it?  Also note changes to this file require a restart so ideally the file will be in it's final state when MQ is started.

**Comment by arthurbarr** [comment]
We don't have a better way of configuring this at the moment, other than directly editing the qm.ini file after the Queue Manager has been created.  Sadly, the `setmqini` command is appliance-specific, and not included in the regular Linux version.

We do have some very basic code to read values from the qm.ini in the [`internal/mqini`](
https://github.com/ibm-messaging/mq-container/tree/master/internal/mqini) package

**Comment by smikishk** [comment]
Thanks @arthurbarr will put something together based off your example.

**Comment by Ivansamara** [comment]
You can mount your *.ini file to /etc/mqm/ directory. Settings form *.ini will merge with qm.ini file

**Comment by smikishk** [comment]
That works, thanks!
