### ISSUE TITLE
Cannot copy mqwebuser.xml to /var/mqm/../mqweb/ folder on container startup

### ISSUE THREAD

**Issue by APC02** [ibm-messaging/mq-container#296]
Hi,

I am trying to copy a custom mqwebuser.xml file for web console configuration in kubernetes deployment. But I am not able to copy the file to directory /var/mqm/web/installations/Installation1/servers/mqweb.  Is there a way I can pass this file when the conatiner starts.

Regards,
Anil

**Comment by arthurbarr** [comment]
Any files or directories written to `/etc/mqm/web` will be copied over to the matching path under `/var/mqm/web` (see [code](https://github.com/ibm-messaging/mq-container/blob/master/cmd/runmqserver/webserver.go#L113)).  So if you drop your `mqwebuser.xml` into `/etc/mqm/web/installations/Installation1/servers/mqweb`, then it should work.

**Comment by APC02** [comment]
Hi @arthurbarr ,

I tried the same. I am able to mount config.mqsc , but when i copy file to /etc/mqm/web/installations/Installation1/servers/mqweb directory, I get the below error.

[MQ-deployment-log.txt](https://github.com/ibm-messaging/mq-container/files/3030761/MQ-deployment-log.txt)
[MQ-deployment-yaml.txt](https://github.com/ibm-messaging/mq-container/files/3030762/MQ-deployment-yaml.txt)
