### ISSUE TITLE
Getting this error while Runing the docker image 

### ISSUE THREAD

**Issue by gocoolharsh** [ibm-messaging/mq-container#299]
DF-585770-MacBook-Pro:mq-container $ docker run -e DISPLAY=$(ipconfig getifaddr en0):0 -v /tmp/.X11-unix:/tmp/.X11-unix -u 0 -ti mq-explorer:latest

(process:1): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
No protocol specified
MQExplorer: Cannot open display: 

(process:30): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
No protocol specified
MQExplorer: Cannot open display: 
No protocol specified
No protocol specified
MQExplorer:
An error has occurred. See the log file
/root/IBM/WebSphereMQ/workspace-Installation1/.metadata/.log.

**Comment by MohitAgrawal1** [comment]
I am also getting the same issue. How did you sort it out ?

**Comment by gocoolharsh** [comment]
I ran this command in XQuartz instead of in terminal , try this .

**Comment by MohitAgrawal1** [comment]
Thanks.

I have tried now to run this command in XQuartz Terminal. However still getting the same issue. I am having XQuartz 2.7.10 version

**Comment by gocoolharsh** [comment]
try this in XQuartz  (  xhost + $(ipconfig getifaddr en0) )
