### ISSUE TITLE
Unable to run in the Ubuntu18.04

### ISSUE THREAD

**Issue by wyuan** [ibm-messaging/mq-container#306]
$ docker-compose -f //MQ/ibmmq/ibmmq_tls.yml up
Starting ibmmq_ibmmq_1 ... done
Attaching to ibmmq_ibmmq_1
ibmmq_1  | 2019-04-29T03:02:04.104Z CPU architecture: amd64
ibmmq_1  | 2019-04-29T03:02:04.104Z Linux kernel version: 4.15.0-47-generic
ibmmq_1  | 2019-04-29T03:02:04.104Z Container runtime: docker
ibmmq_1  | 2019-04-29T03:02:04.104Z Base image: Ubuntu 16.04.6 LTS
ibmmq_1  | 2019-04-29T03:02:04.105Z Running as user ID 999 () with primary group 999, and supplementary groups 0
ibmmq_1  | 2019-04-29T03:02:04.105Z Capabilities (bounding set): chown,dac_override,fowner,fsetid,kill,setgid,setuid,setpcap,net_bind_service,net_raw,sys_chroot,mknod,audit_write,setfcap
ibmmq_1  | 2019-04-29T03:02:04.105Z seccomp enforcing mode: filtering
ibmmq_1  | 2019-04-29T03:02:04.105Z Process security attributes: docker-default (enforce)
ibmmq_1  | 2019-04-29T03:02:04.221Z Set password for "admin" user
ibmmq_1  | 2019-04-29T03:02:08.688Z Using queue manager name: talend_qmgr_tls
ibmmq_1  | 2019-04-29T03:02:08.689Z Error: Unable to change ownership of /mnt/mqm/data
ibmmq_1  | 2019-04-29T03:02:08.689Z chown /mnt/mqm/data: operation not permitted
ibmmq_ibmmq_1 exited with code 1

The docker compose file looks like:
bmmq:
  image: ibmcom/mq
  hostname: ibmmq
  ports:
    - "1414:1414"
    - "9443:9443"
  environment:
    - LICENSE=accept
    - MQ_QMGR_NAME=qmgr_tls
    - MQ_TLS_KEYSTORE=/mnt/mqm/ibmmq.keystore.p12
    - MQ_TLS_PASSPHRASE=*****
  volumes:
    - /MQ/ibmmq/ibmmq-tls:/mnt/mqm

I guessed the problem is caused by **Running as user ID 999 () with primary group 999, and supplementary groups 0**, but not knowing how to fix it. Thanks for your help!

**Comment by arthurbarr** [comment]
It looks like you are using a bind-mounted volume from your host's filesystem.  The files in that directory need to be owned by the `mqm` user (UID 999, GID 999), but they aren't, and MQ doesn't have permission to change them.  You have two choices:

1. Change `/MQ/ibmmq/ibmmq-tls` folder to be owned by 999:999
2. Run the container with an entrypoint of "runmqserver -i" and the root user, and it will correct the permissions on the volume.  You can then run it as normal after that.
