### ISSUE TITLE
BUilding MQ image getting error:failed to set bridge addr: "cni0"

### ISSUE THREAD

**Issue by har2103** [ibm-messaging/mq-container#309]
While building an image getting below exception.

Build go programs
IMAGE_REVISION=3fb2d3fe61a886aecc590219ede4719a202a7888 IMAGE_SOURCE=https://github.com/ibm-messaging/mq-container.git sudo --preserve-env mq-advanced-server-rhel/godk:9.1.2-x86_64-rhel" ""
ERRO[0000] Error adding network: failed to set bridge addr: "cni0" already has an IP address different from 10.88.0.1/16
ERRO[0000] Error while adding pod to CNI network "podman": failed to set bridge addr: "cni0" already has an IP address different from 10.88.0.1/16
error configuring network namespace for container 772964a166388c87b39f3cac287e58e96d063120c737a214bf322dd3de23d734: failed to set bridge addr: "cni0" already has an m 10.88.0.1/16
make: *** [build-go-programs] Error 127

**Comment by arthurbarr** [comment]
Which version of podman are you using?  We've not come across this error.  It's possible that the problem lies with the `--network` option in the [mq-advanced-server-rhel/go-buildah.sh](https://github.com/ibm-messaging/mq-container/blob/9.1.2/mq-advanced-server-rhel/go-buildah.sh) script

**Comment by har2103** [comment]
HI team,

Can you help me change the location to OCI compliant archive file to /tmp/mq-buildah. to something else.

**Comment by arthurbarr** [comment]
I would strongly recommend that you don't build directly off the "master" branch, as documented in the [README](https://github.com/ibm-messaging/mq-container/blob/master/README.md).  This code is in development, and may not always be completely stable.

If you really need to use the current in-development code, then you can change the location of the OCI archive in the [mq-buildah](https://github.com/ibm-messaging/mq-container/blob/master/buildah/mq-buildah) script.  Note that as this is in-development, this may change at any time.  The use of the mq-buildah script is currently just for this point-in-time, until Red Hat release a newer version of Podman, after which this may change again.  In the 9.1.2 branch, the buildah native scripts are still used.

I think there are now three separate issues covered by this GitHub issue.  Could I ask you to please open a new issue if there is still something you'd like us to address?  Please include details such as which host OS you are using, which version of MQ, and which build command.
