### ISSUE TITLE
Qmgr name env variable generates error when using a volume

### ISSUE THREAD

**Issue by markusleonardsabr** [ibm-messaging/mq-container#311]
Adding the MQ_QMGR_NAME env variable to the run statement works fine unless the --volume option is used also.  It generates an invalid reference format error

**docker run --env LICENSE=accept –-env MQ_QMGR_NAME=QM1 --detach --publish 1414:1414 --publish 9443:9443 --name myMQ --volume qm1data:/mnt/mqm ibmcom/mq**
docker: invalid reference format.
See 'docker run --help'.

However, when the MQ_QMGR_NAME env variable is removed, the container will run.  The queue manager that is created seems to be named with a portion of the container id.  

**docker run --env LICENSE=accept --detach --publish 1414:1414 --publish 9443:9443 --name myMQ --volume qm1data:/mnt/mqm ibmcom/mq**
af807ac244764710fda7e4955783d6a25631215572b1a2863c0f46848baf2bcd
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                                      NAMES
af807ac24476        ibmcom/mq           "runmqdevserver"    42 seconds ago      Up 10 seconds       0.0.0.0:1414->1414/tcp, 0.0.0.0:9443->9443/tcp, 9157/tcp   myMQ

**Comment by arthurbarr** [comment]
It looks like you've got an invalid character in the second `--env` in your first command.  The first character isn't a hyphen, which is what Docker was complaining about.  I tried with that corrected, and it seemed to work OK.
