### ISSUE TITLE
Unable to get web ui of IBM Websphere mq image.

### ISSUE THREAD

**Issue by gbalipalli** [ibm-messaging/mq-container#321]
We are trying to spin up a Stateful MQ manager with Azure File System as persistent storage mounted for data in an Azure Kubernetes cluster. Here is the [https://github.com/IBM/charts/tree/master/stable/ibm-mqadvanced-server-dev](url) which we followed. We exposed the service type as LoadBalancer as shown in below command. 
`helm install stable/ibm-mqadvanced-server-dev --version 3.0.1 --set service.type=LoadBalancer,security.initVolumeAsRoot=true,license=accept`

By default,  it takes default storage class as Azure disk. so, I have created storage class for Azure Files and referenced it using `dataPVC.storageClassName`. Now the command would be
`helm install stable/ibm-mqadvanced-server-dev --version 3.0.1 --set dataPVC.storageClassName=azurefile,service.type=LoadBalancer,security.initVolumeAsRoot=true,license=accept`.

After this, we can able to deploy the mq pod in Azure Kubernetes, but pod gets restarted multiple times and generating the logs as `Error: Unable to change ownership of /mnt/mqm/data 2019-05-24T15:22:07.547Z chown /mnt/mqm/data: operation not permitted` and unable to get web ui of MQ.
so, what might be the issue?

**Comment by arthurbarr** [comment]
It looks like neither the "mqm" nor the "root" user are authorized to update file ownership on the persistent volume.  The [Azure docs](https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv#mount-options) indicate that you can set mount options as part of the Storage Class.  Do you know which values you are using?  It may be that these need to be adjusted to allow MQ to change the ownership of the files to the "mqm" user.

**Comment by gbalipalli** [comment]
Hi @arthurbarr. Here is my Storage Class configuration which I am giving,

`kind: StorageClass
 apiVersion: storage.k8s.io/v1
 metadata:
   name: azurefile
 provisioner: kubernetes.io/azure-file
 mountOptions:
   - dir_mode=0755
   - file_mode=0755
   - uid=1000
   - gid=1000
 parameters:
   skuName: Standard_LRS `

I also have tried with ` dir_mode=0777,file_mode=0777, uid=1000,gid: 0`. In that case also getting the same error as `Error: Unable to change ownership of /mnt/mqm/data 2019-05-30T14:47:52.281Z chown /mnt/mqm/data: operation not permitted`. so, how should I give the permissions inorder to allow the MQ to the ownership of the files to the `mqm` user? Can you please help me on this?

**Comment by arthurbarr** [comment]
I'd suggest trying to set `uid=999,gid=999`, as that's the UID and GID of the "mqm" user.

Note that the UID and GID are changing to 888 in the upcoming release, as we're rebasing on Red Hat Universal Base Image.  So if you built off a recent "master" branch, then you may need to use 888 instead.

**Comment by gbalipalli** [comment]
Thanks, @arthurbarr. I will try and let you know. which values should I continue with dir_mode and file_mode either `0777` or `0755`?

**Comment by arthurbarr** [comment]
If the UID/GID gets set correctly, then I think `0755` should probably work OK.

**Comment by gbalipalli** [comment]
After, giving these values `dir_mode=0755,file_mode=0755, uid=999,gid=999`, getting the error like,

    2019-05-30T16:56:48.340Z Starting web server
    2019-05-30T16:56:53.650Z Error 22 starting web server:
    Starting server mqweb.
    Server mqweb start failed. Check server logs for details.

    2019-05-30T16:57:07.113Z crtmqm returned 71
    2019-05-30T16:57:07.113Z AMQ8101S: IBM MQ error (893) has occurred.

    2019-05-30T16:57:07.114Z /usr/bin/crtmqm: exit status 71

**Comment by arthurbarr** [comment]
IBM has formally tested Azure Files for compatibility, and found that it does not meet the requirements for use with IBM MQ.  See https://www.ibm.com/support/pages/node/136799 for more information.
