### ISSUE TITLE
Quemanager is ended unexpectedly while running on kubernetes

### ISSUE THREAD

**Issue by hemangg** [ibm-messaging/mq-container#325]
mqpod.yaml file

apiVersion: v1
kind: Pod
metadata:
  name: mqservice
spec:
  securityContext:
    fsGroup: 999
    runAsUser: 0
  containers:
  - name: mqservice
    image: ibmcom/mq:9.1.2.0
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ] 
    args: [ "while true; do sleep 30; done;" ]
    env:
    - name: LICENSE
      value: "accept"
    - name: MQ_QMGR_NAME
      value: "QM1"
    ports:
    - containerPort: 1414
      name: "defaultport"
    - containerPort: 9443
      name: "listernerport"
    volumeMounts:
      - mountPath: "/mnt/mqm"
        name: azure
  volumes:
      - name: azure
        persistentVolumeClaim:
         claimName: pv-claim

Now I am running it as follows

root@kubemaster-node:~# kubectl create -f mqpod.yaml
pod/mqservice created

root@kubemaster-node:~# kubectl logs mqservice

Now when I go inside the pod and check  whether the queue manager is created it comes as follows

root@kubemaster-node:~# kubectl exec -it mqservice bash
(mq:9.1.2.0)root@mqservice:/# dspmq
QMNAME(QM1)                                               STATUS(Ended unexpectedly)

errors log file

----- amqxfdcx.c : 906 --------------------------------------------------------
06/01/19 15:10:52 - Process(193.15) User(root) Program(amqzmuc0)
                    Host(mqservice) Installation(Installation1)
                    VRMF(9.1.2.0)
                    Time(2019-06-01T15:10:52.141Z)
                    ArithInsert1(193)
                    CommentInsert1(QM1)

AMQ6184W: An internal IBM MQ error has occurred on queue manager QM1.

**Comment by har2103** [comment]
hi, how did you resolve this. i am having same issue when mounting /mnt/mqm.
