### ISSUE TITLE
Quemanager is ended unexpectedly while running on kubernetes

### ISSUE THREAD

**Issue by dhaneshande** [ibm-messaging/mq-container#326]
mqpod.yaml file

apiVersion: v1
kind: Pod
metadata:
  name: mqservice
spec:
  securityContext:
    fsGroup: 999
    runAsUser: 0
  containers:
  - name: mqservice
    image: ibmcom/mq:9.1.2.0
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ] 
    args: [ "while true; do sleep 30; done;" ]
    env:
    - name: LICENSE
      value: "accept"
    - name: MQ_QMGR_NAME
      value: "QM1"
    ports:
    - containerPort: 1414
      name: "defaultport"
    - containerPort: 9443
      name: "listernerport"
    volumeMounts:
      - mountPath: "/mnt/mqm"
        name: azure
  volumes:
      - name: azure
        persistentVolumeClaim:
         claimName: pv-claim

Now I am running it as follows

root@kubemaster-node:~# kubectl create -f mqpod.yaml
pod/mqservice created

root@kubemaster-node:~# kubectl logs mqservice

Now when I go inside the pod and check whether the queue manager is created it comes as follows

root@kubemaster-node:~# kubectl exec -it mqservice bash
(mq:9.1.2.0)root@mqservice:/# dspmq
QMNAME(QM1) STATUS(Ended unexpectedly)

errors log file

----- amqxfdcx.c : 906 --------------------------------------------------------
06/01/19 15:10:52 - Process(193.15) User(root) Program(amqzmuc0)
Host(mqservice) Installation(Installation1)
VRMF(9.1.2.0)
Time(2019-06-01T15:10:52.141Z)
ArithInsert1(193)
CommentInsert1(QM1)

AMQ6184W: An internal IBM MQ error has occurred on queue manager QM1.

**Comment by arthurbarr** [comment]
It looks like you might be running as the "root" user.  The `ibmcom/mq:9.1.2.0` image requires you to run as the "mqm" user.

**Comment by har2103** [comment]
Hi,

I am having same issue. i am trying to deploy on OpenShift and trying to mount /mnt/mqm. i am running as mqm user only.

When i dont mount it work fine for me.

So want to know how can i persist the data for MQ.

Any suggestion will be helpful.

**Comment by atulsingh0** [comment]
I am also facing the same issue when triggering mq process - 
```
2019-06-14T13:05:52.950Z Capabilities (bounding set): chown,dac_override,fowner,fsetid,setpcap,net_bind_service,net_raw,sys_chroot,audit_write,setfcap
2019-06-14T13:05:52.950Z seccomp enforcing mode: disabled
2019-06-14T13:05:52.950Z Process security attributes: system_u:system_r:container_t:s0:c7,c28
2019-06-14T13:05:52.950Z No volume detected. Persistent messages may be lost
2019-06-14T13:05:52.950Z Error: Unable to change ownership of /mnt/mqm/data
2019-06-14T13:05:52.950Z chown /mnt/mqm/data: operation not permitted
```

few details are as below -
```drwxrwxr-x.   1 mqm        root          4096 Dec 14  2017 media
drwxrwxr-x.   1 mqm        root          4096 Jun 13 19:52 mnt```

Pod config:
```openshift.io/scc: restricted
  serviceAccountName: default```

**Comment by arthurbarr** [comment]
@atulsingh0 MQ cannot currently run under the "restricted" OpenShift SCC.  See issue #197
