### ISSUE TITLE
unable to mount /mnt/mqm/data on glusterFS openshift 

### ISSUE THREAD

**Issue by har2103** [ibm-messaging/mq-container#331]
Hi Team,

i am using ace+mq image provided by ibm ( on june 24th)and deploying on openshift. it work fine when i don't mount.

But i mount /mnt/mqm/data to glusterFS my queue manager doesn't comes up and status of queue manager is “Ended unexpectedly”.

+-----------------------------------------------------------------------------+
|                                                                             |
| IBM MQ First Failure Symptom Report                                         | 
| =========================================                                   | 
|                                                                             |
| Date/Time         :- Wed June 05 2019 20:10:35 UTC                          | 
| UTC Time          :- 1559765435.447315                                      | 
| UTC Time Offset   :- 0 (UTC)                                                | 
| Host Name         :- pvc-ibm-ace-mq-785bd79d58-wsvxx                        | 
| Operating System  :- Linux 3.10.0-957.1.3.el7.x86_64                        | 
| PIDS              :- 5724H7251                                              | 
| LVLS              :- 9.1.0.0                                                | 
| Product Long Name :- IBM MQ for Linux (x86-64 platform)                     | 
| Vendor            :- IBM                                                    | 
| O/S Registered    :- 1 (libmqmcs_r.so)                                      | 
| Data Path         :- /var/mqm                                               | 
| Installation Path :- /opt/mqm                                               | 
| Installation Name :- Installation1    (1)                                   | 
| License Type      :- Production                                             | 
| Probe Id          :- ZX165131                                               | 
| Application Name  :- MQM                                                    | 
| Component         :- zmuUtilityManager                                      | 
| SCCS Info         :- /build/slot1/p910_P/src/lib/zu/amqzmut0.c,             | 
| Line Number       :- 1223                                                   | 
| Build Date        :- Jul  5 2018                                            | 
| Build Level       :- p910-L180705                                           | 
| Build Type        :- IKAP - (Production)                                    | 
| Effective UserID  :- 888 (mqm)                                              | 
| Real UserID       :- 888 (mqm)                                              | 
| Program Name      :- amqzmuc0                                               | 
| Arguments         :- -m hub                                                 | 
| Addressing mode   :- 64-bit                                                 | 
| LANG              :- en_US.UTF-8                                            | 
| Process           :- 25619                                                  | 
| Process(Thread)   :- 25619                                                  | 
| Thread            :- 1    Critical                                          | 
| QueueManager      :- hub                                                    | 
| SubpoolName       :- hub                                                    | 
| UserApp           :- FALSE                                                  | 
| ConnId(1) IPCC    :- 5                                                      | 
| ConnId(2) QM      :- 7                                                      | 
| Last HQC          :- 2.0.0-2404736                                          | 
| Last HSHMEMB      :- 2.4.0-12918720                                         | 
| Last ObjectName   :-                                                        | 
| Major Errorcode   :- zrcE_UNEXPECTED_ERROR                                  | 
| Minor Errorcode   :- OK                                                     | 
| Probe Type        :- INCORROUT                                              | 
| Probe Severity    :- 2                                                      | 
| Probe Description :- AMQ6125E: An internal IBM MQ error has occurred.       | 
| FDCSequenceNumber :- 0                                                      | 
|                                                                             |
+-----------------------------------------------------------------------------+

**Comment by arthurbarr** [comment]
I'm sorry for the delay in responding.  I'm afraid that I don't think there's enough information here for us to debug.  We have seen a number of problems with IBM MQ on Gluster.  Our [testing statement](https://www-01.ibm.com/support/docview.wss?uid=swg21433474) indicates the versions of Gluster we have already found that don't meet MQ's requirements for file systems.
