### ISSUE TITLE
search port 9443 for REST API

### ISSUE THREAD

**Issue by pcouas** [ibm-messaging/mq-container#337]
Hi,

I don't see any port 9443 for REST API in your dockerfile ?
Which current dockerfile use RESTAPI
Do you have webconsole in this docker ?

Regards
OK i found
https://hub.docker.com/r/ibmcom/mq
/c/Program\ Files/Docker\ Toolbox/docker pull ibmcom/mq
/c/Program\ Files/Docker\ Toolbox/docker run \
  --env LICENSE=accept \
  --env MQ_QMGR_NAME=QM1 \
  --publish 1414:1414 \
  --publish 9443:9443 \
  --detach \
  ibmcom/mq

https://localhost:9443/ibmmq/console/login.html

**Comment by arthurbarr** [comment]
Yes, the web server is enabled.  Having the `PORT` in the Dockerfile is optional, and doesn't affect the runtime, unless you tell Docker to expose all ports with the `--publish-all` flag.
