### ISSUE TITLE
connexion not possible from MQMON

### ISSUE THREAD

**Issue by pcouas** [ibm-messaging/mq-container#341]
Your Webconsole on port 9443 is not complete  (no process for example)
I have tried MQMON tool on channel name 'DEV.ADMIN.SVRCONN' created automatically on install without succes
Do you have an complete connection example
Regards

**Comment by arthurbarr** [comment]
Can you be more specific about what you're asking for here?  The web server is only enabled in either a.) the MQ Advanced for Developers image; or b.) the in-development version of the MQ Advanced image from the "master" branch, if you set the `MQ_ENABLE_EMBEDDED_WEB_SERVER` environment variable to `true`.

I don't understand how the web server relates to an MQ SVRCONN channel.  Channels are for MQ client connections, and not for HTTP connections.

**Comment by pcouas** [comment]
Ok 
Currently i check with last 9.1.2 docker, if we replace our Java PCF library by your new REST API
Our company use all MQ objects like Channel or Process (71000 Queues, 23000 Process in production)
For my tests i have added by rest command 'mqsc' some new PROCESS, but i could not check them in your webconsole.
So we have too MQMON tool and i search how connect 'DEV.ADMIN.SVRCONN' which is created automatically by install Docker for viewing if all objects and verify if they arre well created.

**Comment by arthurbarr** [comment]
I don't think this is specifically a container issue, but a more general MQ issue.  Can I please ask you to raise a PMR, so that the right person can be assigned to help you?
