### ISSUE TITLE
Dead Letter Queue Handling in CaaS MQ Environment

### ISSUE THREAD

**Issue by lsabados** [ibm-messaging/mq-container#352]
How would we go about implementing a Dead Letter Queue Handler in an MQSeries QMgr CaaS pod?
How would we create (at the time of the MQ pod deployment) the DLQH rules table and create a DLQH script on the QMgr's pod?

**Comment by arthurbarr** [comment]
Sorry for the delay in responding.  You can run any MQSC you like at container start time, by dropping MQSC files into `/etc/mqm` with the extension `.mqsc`.  You can invoke a dead letter handler either via an MQ service, or as a manual command (e.g. `docker exec` or `kubectl exec`).  If you have a custom handler, then you can add the script for that as a container image layer.
