### ISSUE TITLE
Verify only one instance is running doesn't work with sudo

### ISSUE THREAD

**Issue by vschurink** [ibm-messaging/mq-container#358]
Hi Peeps,

When trying to run this in a docker with an upgrade path from 9.1.1 to 9.1.3 we were running into issues where we kept getting the error "You cannot run more than one instance of this program"

It appears you run the verification with ps -ef and see how many runmqserver processes are in the list, with more then 1 giving this error.

The issue is that when you use sudo to do the runmqserver, because you want to automate the upgrade in a docker container entrypoint script, this fails due to your verification function not taking into account that sudo can be called to run mqserver.

We are working around this now with a bash script, however this seems an oversight on your part.

Furthermore it's kind of silly that you introduce a breaking change (ui/guid) rename without offering a valid and automated upgrade path within runmqserver (as you have to run it as root, you say so yourself) since your default sudoers.d file only allows a password change.

function that causes the issue: https://github.com/ibm-messaging/mq-container/blob/8fd818444580f68c08c935139aecf32f2a54c2de/cmd/runmqserver/process.go#L44

thanks in advance
VS

**Comment by smikishk** [comment]
Container images are immutable, so not sure what you mean by "upgrade"?

**Comment by arthurbarr** [comment]
It sounds like you might be trying  to do an MQ install inside a running container. That is not how upgrades should be done with containers.  Instead, you should create another MQ image with the new version installed. You can then delete the original container, and run a new container based on your new image. We run `crtmqdir` at container startup, which will upgrade your data files if needed (which naturally need to live in a separate volume).

**Comment by vschurink** [comment]
Hi Guys,

thanks for the responses.  We are just running the new docker containers, however when you guys released version 9.1.2.0 you introduced a breaking change in that you change the G/UID of the mqm user see:

> 9.1.2.0-UBI (2019-06-21)
> Breaking changes:
> UID of the mqm user is now 888. You need to run the container with an entrypoint of runmqserver -i under the root user to update any existing files.

now in order to do this inside the container (even though the datafiles are mounted) you need to be root. Since we're running all our infrastructure as code this means that if we wanted to upgrade our running setup(s) we would need a way to script it to ensure that all our datafiles had the new, proper G/UID.

Since the default user is mqm inside the new containers we tried to use sudo for this specific command to resolve the issue without resorting to more drastic measures however that is when we ran into the issue as described, namely that the way you try to prevent running more then one instance of runmqserver is not finegrained enough. 

This is easily reproducible by running a default container then logging in as the default mqm user (though you have to enable sudo) and run `sudo runmqserver -i`. 

You will get the error back that more then 1 instance of runmqserver cannot run, which is silly because running that command is required according to your description in the upgrade steps.

as for the crtmqdir ( i presume you mean crtmqvol?) command, this does not help because the user is MQM inside the container, not root. Therefor the runmqmserver process does not have permission to change the directory owner (if you are upgrading from a previous version) using chmod without running it as root.

hence my suggestion to fix the way you validate if more then 1 runmqserver process is running.

regards

**Comment by arthurbarr** [comment]
What we do in our supported Helm charts for Kubernetes, is run an “init” container before the main container. The init container runs as “root”, using an entry point of “runmqserver -i “, which will update all the file permissions using “crtmqdir”. You can then run the 9.1.2/9.1.3 container as mqm, and it will be fine.

**Comment by vschurink** [comment]
Hi Arthur,

my issue is not that we cannot solve it in a more complex way, but that the current 'failsafe' implementation of ensuring that runmqserver does not run multiple times is not good enough.

It does not enable running runmqserver -i inside the container with sudo, because your ps -ef sees two processes with runmqserver when you run it as sudo, namely, the sudo runmqserver command under user MQM and the process of runmqserver as user root which causes the sudo command to fail with the aforementioned error: `Expected there to be only 1 instance of %s but found %d", programName, numOfProg`

If this is not something you would fix I would recommend closing the issue.

regards

**Comment by arthurbarr** [comment]
I don't understand the need to ever run another instance of "runmqserver" inside an existing container.  "runmqserver" does quite a lot, and it's certainly not been tested to run it while another is already running, which is why the fail-safe is in there.

I described in my previous comment how I think you safely and quickly perform an upgrade *without* running an additional instance (i.e. stop your original container; run a container with `runmqserver -i` as root; run a container based on the new image).  Therefore, I propose we close this issue.
