### ISSUE TITLE
mq image on ubi base image

### ISSUE THREAD

**Issue by har2103** [ibm-messaging/mq-container#359]
Hi Team,

I have build a new mq image and i can see the base image is changed to ubi.

ARG BASE_IMAGE=registry.access.redhat.com/ubi7/ubi-minimal
ARG BASE_TAG=7.6-237

i used the latest mq-conatiner scripts and built mq image.

but when i see the version after deploying in openshift it gives below result.

sh-4.2$ cat /etc/*-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
Red Hat Enterprise Linux Server release 7.6 (Maipo)
Red Hat Enterprise Linux Server release 7.6 (Maipo)

donesnt see ubi its hows maipo ?

can you confirm ?

**Comment by arthurbarr** [comment]
The Red Hat Universal Base Image (UBI) is a strict sub-set of Red Hat Enterprise Linux, which Red Hat has made available to run on any host.  It still reports as Red Hat Enterprise Linux as you have seen, because that's what it really is.
