### ISSUE TITLE
STEP 9: RUN chmod a+x /usr/local/bin/install-mq.sh   && sleep 1   && MQ_PACKAGES="MQSeriesRuntime-*.rpm MQSeriesSDK-*.rpm MQSeriesSamples*.rpm" install-mq.sh $MQM_UID

### ISSUE THREAD

**Issue by VinayakaBS** [ibm-messaging/mq-container#360]
Team

We are getting the below error while building the mq image at STEP 9 in the docker file,

STEP 9: RUN chmod a+x /usr/local/bin/install-mq.sh   && sleep 1   && MQ_PACKAGES="MQSeriesRuntime-*.rpm MQSeriesSDK-*.rpm MQSeriesSamples*.rpm" install-mq.sh $MQM_UID
+ mqm_uid=888
+ test -f /usr/bin/yum
+ YUM=true
+ test -f /usr/bin/microdnf
+ MICRODNF=false
+ test -f /usr/bin/rpm
+ RPM=true
+ test -f /usr/bin/apt-get
+ UBUNTU=false
+ DIR_EXTRACT=/tmp/mq
+ mkdir -p /tmp/mq
+ cd /tmp/mq
+ curl -LO file:///src/downloads/IBM_MQ_9.1.3_LINUX_X86-64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  367M  100  367M    0     0   977M      0 --:--:-- --:--:-- --:--:--  977M
+ tar -zxf ./IBM_MQ_9.1.3_LINUX_X86-64.tar.gz
+ groupadd --system --gid 888 mqm
+ useradd --system --uid 888 --gid mqm --groups 0 mqm
+ false
+ true
++ find /tmp/mq -name '*.rpm' -printf '%h\n'
++ sort -u
++ head -1
+ DIR_RPM=
++ find /tmp/mq -name mqlicense.sh
+ MQLICENSE=
+ -text_only -accept
/usr/local/bin/install-mq.sh: line 46: -text_only: command not found
subprocess exited with status 127
subprocess exited with status 127
                                 error building at STEP "RUN chmod a+x /usr/local/bin/install-mq.sh   && sleep 1   && MQ_PACKAGES="MQSeriesRuntime-*.rpm MQSeriesSDK-*.rpm MQSeriesSamples*.rpm" install-mq.sh $MQM_UID": exit status 127
make: *** [build-advancedserver-ctr] Error 1

Please let us know how to proceed further.

Thanks

**Comment by arthurbarr** [comment]
It looks to me like there's something wrong with the `IBM_MQ_9.1.3_LINUX_X86-64.tar.gz` file, as the code is not able to find the `mqlicense.sh` file inside that TAR file.

1. Can you confirm that your copy of `IBM_MQ_9.1.3_LINUX_X86-64.tar.gz` is 843267226 bytes (which is what my copy is)
2. Can you confirm what the contents of that TAR file looks like (e.g. with a `tar -tvf IBM_MQ_9.1.3_LINUX_X86-64.tar.gz`?

**Comment by VinayakaBS** [comment]
Thanks Arthur Barr for the reply,

PF the steps we did for your review,

1. Downloaded "9.1.3.0-IBM-MS0T-LinuxX64.tar.gz" (Size:376370 KB) from IBM Fix Central page.
2. Extracted "mq-container-master.zip" and created a folder "downloads" under "mq-container-master" folder 
3. And placed "9.1.3.0-IBM-MS0T-LinuxX64.tar.gz" in the "downloads" (mq-container-master/downloads) folder after renaming it as "IBM_MQ_9.1.3_LINUX_X86-64.tar.gz"
4. Then used the command " make build-advancedserver"

Can you please review the above steps, and also kindly provide us the link to download IBM_MQ_9.1.3_LINUX_X86-64.tar.gz with 843267226 bytes

Thanks

**Comment by arthurbarr** [comment]
The file `9.1.3.0-IBM-MS0T-LinuxX64.tar.gz` is a download containing MQ SupportPac MS0T, which is MQ Explorer only.  If you want to build a licensed, production image, then the current latest download is "IBM MQ V9.1.3 Continuous Delivery Release for Linux on x86 64-bit Multilingual (CNZA2ML )" on IBM Passport Advantage.  This will give you the `IBM_MQ_9.1.3_LINUX_X86-64.tar.gz` which you need.
