### ISSUE TITLE
2019-08-16T15:21:02.009Z AMQ8060I: IBM MQ queue manager 'QMGR' started as a standby instance.

### ISSUE THREAD

**Issue by har2103** [ibm-messaging/mq-container#361]
Hi Team,

I have created a ACE+MQ images with MQ version 9.1.2. When i deploy this image in Openshift with one instance(pod) it works fine but when I scale pod to 2 the second pod ends with below error:

2019-08-16T15:21:02.009Z AMQ8060I: IBM MQ queue manager 'QMGR' started as a standby instance.

I just want to know how we can scale up ACE+MQ pod. because we observed that when we are bringing 2 pods up then MQ is going in active passive mode where we want all the MQ in active modes.

can you suggest how we can do that ? or is it possible to do it ?

**Comment by arthurbarr** [comment]
We [don't recommend](https://github.com/IBM/charts/tree/master/stable/ibm-mqadvanced-server-dev#limitations) that you scale MQ by changing the number of replicas in a Stateful Set.  In our supported Helm charts, we use the replicas field to help manage multi-instance queue managers.  The recommendation is to deploy multiple Stateful Sets, and scale MQ in the normal way (e.g. MQ clusters).

**Comment by arthurbarr** [comment]
Also note that the ACE+MQ container image is not managed in this repository.  See the [ace-docker](https://github.com/ot4i/ace-docker) repository for that, to ensure that you get through to the right people for questions about scaling ACE.
