### ISSUE TITLE
Licensing for MQ Advanced

### ISSUE THREAD

**Issue by bony-cas** [ibm-messaging/mq-container#368]
When building with either build-devserver or build-advancedserver the resulting image is classed as 'IBM MQ Advanced' or 'IBM MQ Advanced for Developers'. My understanding is that 'MQ Advanced' has licensing\cost implications. I'd like to understand the implications of this. Should I raise this via my AVP contact? or can you point me in the direction of any statement regarding the licensing of MQ Advanced on docker? Is it possible to build the image without the MQ Advanced components (e.g. AMS) and so, even though the product shows as 'MQ Advanced' we are not actually using any MQ Advanced components and so will not be billed as using 'MQ Advanced'?

Hope this makes sense.

**Comment by callumpjackson** [comment]
The MQ Certified Container includes the Advanced Message Security feature, which causes the container to be considered IBM MQ Advanced. This can be changed with a simple change to the [Makefile](https://github.com/ibm-messaging/mq-container/blob/master/Makefile)
Within the following line:
```MQ_PACKAGES ?=MQSeriesRuntime-*.rpm MQSeriesServer-*.rpm MQSeriesJava*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm MQSeriesMsg*.rpm MQSeriesSamples*.rpm MQSeriesWeb*.rpm MQSeriesAMS-*.rpm```
 
Simply remove the final package **_MQSeriesAMS-*.rpm_**
```MQ_PACKAGES ?=MQSeriesRuntime-*.rpm MQSeriesServer-*.rpm MQSeriesJava*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm MQSeriesMsg*.rpm MQSeriesSamples*.rpm MQSeriesWeb*.rpm```
 
Rebuild the container image, and this will build the image without the AMS package, and therefore be a MQ base container image. This can be verified by checking the Queue Manager configuration:
```
dis QMGR
     1 : dis QMGR
AMQ8408I: Display Queue Manager details.
   QMNAME(QM1)                             ACCTCONO(DISABLED)
   ACCTINT(1800)                           ACCTMQI(OFF)
   ACCTQ(OFF)                              ACTIVREC(MSG)
   ACTVCONO(DISABLED)                      ACTVTRC(OFF)
   ADVCAP(DISABLED)                        ALTDATE(2019-08-29)
   ALTTIME(23.16.37)                       AMQPCAP(NO)
```
