### ISSUE TITLE
memory leak in amqrmppa since version 9.1.3.0

### ISSUE THREAD

**Issue by mvanholsteijn** [ibm-messaging/mq-container#369]
Since we upgraded from ibmcom/mq:9.1.1.0 to ibmcom/mq:9.1.3.0 we experience a serious memory leak in the amqrmppa process, as shown in the graph below.  Until July 22nd, we ran 9.1.1.0 after that 9.1.3.0. Upgrading to  9.1.3.0-r2 did not help either. What can we do to solve this?

![amqrmppa memory leak 9 1 3 0](https://user-images.githubusercontent.com/576619/65128888-923c7d80-d9fa-11e9-8ad4-1a61bbbba41a.jpg)

**Comment by arthurbarr** [comment]
The `amqrmppa` process is part of the MQ product, and not related to this MQ container sample.  Can I please suggest that you open a case with [IBM Support](https://www.ibm.com/mysupport/s/?language=en_US)?
