### ISSUE TITLE
Ubuntu support in the makefile build - RFE

### ISSUE THREAD

**Issue by liz72703** [ibm-messaging/mq-container#375]
The instructions for building the production image say:

_Warning: Note that MQ offers two different sets of packaging on Linux: one is called "MQ for Linux" and contains RPM files for installing on Red Hat Enterprise Linux and SUSE Linux Enterprise Server; the other is for Ubuntu. The MQ container build uses a Red Hat Universal Base Image, so you need the "MQ for Linux" RPM files._

Will support for MQ on Ubuntu be coming in the future?

Thank you,
Liz

**Comment by arthurbarr** [comment]
We have no plans to create container images based on Ubuntu.  We used to have images based on Ubuntu, but have moved entirely to the Universal Base Image, as it offers better support options for most of our customers.  The [core Ubuntu installation code](https://github.com/ibm-messaging/mq-container/blob/master/install-build-deps-ubuntu.sh) has not entirely been removed though, so if you refer to this correctly in your Dockerfile, you can still build on an Ubuntu image.

Our direction is to focus on UBI though, unless we hear a strong demand for anything else (let us know!).
