### ISSUE TITLE
Redhat authentication failure to pull the rhel docker image on macos

### ISSUE THREAD

**Issue by krishnadamarla** [ibm-messaging/mq-container#382]
Regarding, https://github.com/ibm-messaging/mq-container/tree/master/incubating/mq-explorer

Upon ```docker build -t mq-explorer -f ./Dockerfile . ```, below steps are stopping building an image. Any hints or help ? Thank you

```
Sending build context to Docker daemon  4.608kB
Step 1/10 : FROM registry.redhat.io/ubi8/ubi-minimal AS mq-explorer
Get https://registry.redhat.io/v2/ubi8/ubi-minimal/manifests/latest: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```

**Comment by arthurbarr** [comment]
The MQ images are based on Red Hat base images, and Red Hat now requires you to login with a Red Hat ID to pull images.

As per the error, you need to login before you try and build: "Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication"
