### ISSUE TITLE
Use mq-container for tests on github

### ISSUE THREAD

**Issue by SeyfSV** [ibm-messaging/mq-container#383]
Hi all,
Does any body know, can `mq-container` be used for testing in github workflows? Don't it violate license agreement?

**Comment by callumpjackson** [comment]
The mq-container is licensed under the Apache License 2.0, this can be found here: 
https://github.com/ibm-messaging/mq-container/blob/master/LICENSE
This describes the permissions, limitations and conditions of the license and should be used to verify your usage.

**Comment by SeyfSV** [comment]
This Apache license about mq-container: files/codes/etc published in https://github.com/ibm-messaging/mq-container/ repository. But it is not about MQ license.
This is from [README.md](/ibm-messaging/mq-container/blob/master/README.md):

> License
> 
> The Dockerfiles and associated code and scripts are licensed under the Apache License 2.0. Licenses for the products installed within the images are as follows:
> 
>  IBM MQ Advanced for Developers (International License Agreement for Non-Warranted Programs). This license may be viewed from an image using the LICENSE=view environment variable as described above or by following the link above.
>  IBM MQ Advanced (International Program License Agreement). This license may be viewed from an image using the LICENSE=view environment variable as described above or by following the link above.
> 
> Note: The IBM MQ Advanced for Developers license does not permit further distribution and the terms restrict usage to a developer machine.

**Comment by callumpjackson** [comment]
Sorry I mis-understood your question – you are concerned about the license associated with the MQ binaries, instead of the code within the mq-container github. If you are creating an automated build then you should consult the MQ license agreement prior to creating the pipeline and assure that you logic will not break any of the license terms.

**Comment by SeyfSV** [comment]
I think I found answer: yes, it can be used, and no, it is not violate license agreement:
[License Information document](https://www-03.ibm.com/software/sla/sladb.nsf/lilookup/1BED147E20AC2F0D852584330065394B?OpenDocument), link to same document exists in `mq-container` LICENSE (I don't know why I did not found Developer Limitation on first read).
> Developer Limitation
>
> If the Program is designated as for "Developers", the Program can only be deployed as part of Licensee's internal development and unit testing on a developer machine. A developer machine is a physical or virtual desktop environment, running a primary operating system and the Program, both of which are accessible and used by no more than one specified developer. Licensee is not authorized to use the Program for processing production workloads, simulating production workloads or testing scalability of any code, application or system. Licensee is not authorized to use any part of the Program for any other purposes without acquiring the appropriate production entitlements.
