### ISSUE TITLE
Config map not applying following Update and pod restart

### ISSUE THREAD

**Issue by lsabados** [ibm-messaging/mq-container#385]
Hello.

We are using the MQ v9.0.5.0 image with OpenShift deployment.  We have seen behavior, of MQ in a pod following a configmap update and pod restart.  The pod restarts and goes to a "Ready" status, but , in the OpenShift MQ log, the QMgr reaches the point where the channel initiator starts, but the configmap is not applied.  We think that connecting applications are causing this.  Is there a way around having to stop the connecting application (WAS liberty) before restarting the pod?

**Comment by callumpjackson** [comment]
As this is a customization of the repo - lets take this off-line to discuss.

**Comment by arthurbarr** [comment]
I assume this was resolved offline.  Please feel free to re-open if not.
