### ISSUE TITLE
How to add user?

### ISSUE THREAD

**Issue by sudarshanaks** [ibm-messaging/mq-container#388]
is there way I can add ldap user or normal user without building image again and again?

**Comment by arthurbarr** [comment]
Local OS users (e.g. via `useradd`) are local to the container, and require a re-build as the root user.  However, if you [configure MQ to use LDAP](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q085490_.htm#q085490___7) then the users can be added and managed in the LDAP server.

**Comment by sudarshanaks** [comment]
Can I configure this ldap   & add user from MQ console or do need to modify this docker image to configure ldap?

**Comment by arthurbarr** [comment]
You can [customize the Queue Manager configuration](https://github.ibm.com/mq-cloudpak/mq-container/blob/28291306cb427f69069347223b975da86b763a47/docs/usage.md#customizing-the-queue-manager-configuration) using an MQSC file which will get applied at runtime.  You should also ensure you use a persistent volume mounted to `/mnt/mqm` to ensure that configuration changes are persisted across container restarts.
