### ISSUE TITLE
System could not dynamically load the shared library

### ISSUE THREAD

**Issue by Seeker911** [ibm-messaging/mq-container#390]
I have setup the MQ container on my windows 10 machine using Linux containers. I can access the web interface using this uri "https://localhost:9443/ibmmq/console/" and everything seems to work. However I cannot connect to the MQ instance I get an error saying host could not be reached. I can telnet to the port. Looking at the logs however I get this error message.

2020-03-25T20:29:02.613Z AMQ6255E: The system could not dynamically load the shared library '/opt/mqm/lib64/libedit.so'.
2020-03-25T20:29:02.614Z AMQ6175E: The system could not dynamically load the shared library '/opt/mqm/lib64/libedit.so'. The system returned error message 'libncurses.so.5: cannot open shared object file: No such file or directory'.

if i run "ldd libedit.so" using bash I get:
libncurses.so.5 => not found
libtinfo.so.5 => not found

**Comment by arthurbarr** [comment]
The libedit error is a known bug in MQ, and is nothing to worry about.

How are you trying to connect?  What configuration are you using for MQ?  It's worth noting that MQ is not typically configured out of the box — it will be listening on TCP, but won't allow any connections — you need to configure it yourself.  The exception is our MQ Advanced for Developers image, which *is* pre-configured.

**Comment by Seeker911** [comment]
Hi Arthur

I have a .net client app that currently connects to our production IBM MQ's I used that initially but could not connect. I did change the config.

I then tried this image and got the same issue : 
docker run --rm --name mydemoibmmqclient --network mq-dev-network -ti mq-demo

the output is shown below:

![Capture](https://user-images.githubusercontent.com/19358809/77742738-9daed800-701f-11ea-85ec-29c13b3125ba.PNG)

**Comment by arthurbarr** [comment]
Assuming you're using the pre-configured developer image for the server, then the issue I can see in the above example is that the client's connecting to `localhost`.  You'd need to make sure you specify the IP address or host name of the queue manager, on the `mq-dev-network` network.

**Comment by Seeker911** [comment]
Yes. You are correct. By specifying the actual IP of my machine it works fine. 

Much appreciated for your time and help.
