### ISSUE TITLE
MQ HA In Containers - Success Stories?

### ISSUE THREAD

**Issue by lsabados** [ibm-messaging/mq-container#398]
Hello-
My organization is in need of a MQ HA capability with MQ in containers.  We currently rely on the single resilient QMgr pods. With recent issue with our environment (kubernetes workers failing) it has become evident that we need failover MQ pods.  We tried replicants, but when the "promary" pod fails, the standbywill only handle new messages (messages in failed MQ pod are unavailable).  Also, remote MQ connections (SDR/RCV channels) suffer sequence number issues when connecting to the standby MQ pod.  Has anyone successfully implemented MQ HA in a CaaS (kubernetes) environment, using shared storage or some other way of replicating the messages amongst the MQ replicant pods?

**Comment by callumpjackson** [comment]
As discussed we will hold a call and then document any important aspects here. Closing for the moment.
