### ISSUE TITLE
Docker hub page shows deprecated source repository

### ISSUE THREAD

**Issue by chughts** [ibm-messaging/mq-container#399]
The Docker Hub home page for ibmcom/mq is showing the deprecated repository ibm-messaging/mq-docker as the source page for the image. This should be corrected.

**Comment by arthurbarr** [comment]
Unfortunately, Docker do not allow that field to be changed!

**Comment by arthurbarr** [comment]
This no longer seems to appear on the Docker Hub page, and it shows that the `ibmcom/mq` image isn't linked to a GitHub repository.
