### ISSUE TITLE
Seems like the container is no longer creating the groups mqclient and mqm

### ISSUE THREAD

**Issue by chughts** [ibm-messaging/mq-container#400]
There have been 2 recent questions on StackOverflow implying that the current container (9.1.5.0-r1) image is no longer creating the groups mqclient and mqm. 

https://stackoverflow.com/questions/61373195/ibmcom-mq-docker-image-backward-compatibility-issue#comment108710567_61373195

and 

https://stackoverflow.com/questions/61601607/mq-custom-docker-image-mqm-group-not-found

The docker file in this repo is creating both, but it hasn't been updated since Dec 3, 2019, so it might not be reflecting what is being published to docker hub.

**Comment by agebhar1** [comment]
It's also reported in #394 and #395

**Comment by arthurbarr** [comment]
Correct.  The code for the latest image on Docker Hub intentionally removes the use of OS users and groups.  This is based on the security recommendations from Red Hat for running containers in Red Hat OpenShift Container Platform.  Users should use LDAP to authenticate users.

The latest code used to build the MQ 9.1.5 image on Docker Hub has not yet been published in this repository, but the plan is to do so in the future.
