### ISSUE TITLE
Changing qm.ini on MQ on CP4I 

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-container#405]
How do you modify the qm.ini when deploying MQ on Cloud Pak for Integration (Openshift)?
CP4I: 2020.1.1
MQ: 9.1.4
Openshift: 4.3

**Comment by arthurbarr** [comment]
This repo is for issues with our sample container image.  The image allows you to put INI files in the `/etc/mqm` directory, and they will be passed to the queue manager for merging at start time.  You need to build a custom image layer on top of the MQ image, which adds whatever INI files you want to merge.
