### ISSUE TITLE
[ HELP ] How to add users when using IBM MQ in Contianer

### ISSUE THREAD

**Issue by Nirothipan** [ibm-messaging/mq-container#411]
I'm using the docker container and would like to add some messaging level users. I followed this https://www.ibm.com/support/knowledgecenter/SS5K6E_9.0.0/com.ibm.mqa.doc/reference/usercmd/userintro.htm however it is not clear where to run these commands when using the docker container. Could someone please guide on this @arthurbarr

**Comment by Nirothipan** [comment]
Or should this user creation be done in appliance (https://www.ibm.com/support/knowledgecenter/en/SS5K6E_9.1.0/com.ibm.mqa.doc/overview/ov00050.htm )  or sthng. could some one guide me on this

**Comment by arthurbarr** [comment]
The documentation you've referenced there is for the MQ Appliance (hardware).

Up until MQ 9.1.4, you could add OS users with a container image layer as [documented in the MQ Knowledge Center](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.ctr.doc/q114495_.htm).  *However* we generally recommend against this for security reasons, and instead recommend the use of LDAP.

From MQ 9.1.5 onwards, the MQ certified containers prohibit use of local OS users, so you *must* use LDAP.

Also see [User authentication and authorization for IBM MQ Advanced certified container](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.ctr.doc/auth_for_ctr.htm)

**Comment by Nirothipan** [comment]
Thanks @arthurbarr .
