### ISSUE TITLE
duplicate entries in qm.ini

### ISSUE THREAD

**Issue by hpoluru999** [ibm-messaging/mq-container#415]
We are using MQ9.1.4. We want to update and add below lines in qm.ini.
Log:
   LogPrimaryFiles=5
   LogSecondaryFiles=50
SSL:
   OCSPCheckExtensions=NO
   OCSPAuthentication=OPTIONAL
Channels:
   MaxActiveChannels=300
   MaxChannels=300

Resulting qm.ini have duplicates. Looks like existing lines were updated correctly but added second line twice if that doesn’t exist.

sh-4.4$ cat qm.ini
:
Log:
   **LogPrimaryFiles=5
   LogSecondaryFiles=50**
   LogFilePages=4096
   LogType=CIRCULAR
   LogBufferPages=0
   LogPath=/var/mqm/log/DEV.QM/
   LogWriteIntegrity=TripleWrite
Service:
   Name=AuthorizationService
   EntryPoints=14
ServiceComponent:
   Service=AuthorizationService
   Name=MQSeries.UNIX.auth.service
   Module=amqzfu
   ComponentDataSize=0
SSL:
   OCSPCheckExtensions=NO
   **OCSPAuthentication=OPTIONAL
   OCSPAuthentication=OPTIONAL**
   AllowTLSV13=TRUE
   MinimumRSAKeySize=1
Channels:
   MaxActiveChannels=300
   **MaxChannels=300
      MaxChannels=300**
   ChlauthEarlyAdopt=Y

**Comment by arthurbarr** [comment]
I think this could be a bug in the INI merging code we used in the MQ 9.1.4 container.  The merging feature was implemented in the core MQ code in MQ 9.1.5, and doesn't show this bug.  Is moving up to MQ 9.1.5 an option for you?

**Comment by hpoluru999** [comment]
I don’t see any issues with these duplicate entries in qm.ini right now. Yes, moving up to MQ9.1.5 is an option for us. Thanks for the explanation. Please close this issue.
