### ISSUE TITLE
[Question] - Error make build-devserver (linux)

### ISSUE THREAD

**Issue by fbsantana2020** [ibm-messaging/mq-container#416]
I received the follow error when I executed the make build-devserver: 

Step 48/97 : RUN env && chmod u+x /usr/local/bin/install-*.sh   && sleep 1   && install-mq-server-prereqs.sh $MQM_UID   && install-mq.sh $MQM_UID
 ---> Running in e8b1cda42187
HOSTNAME=25d9d267b342
MQ_URL=http://build:80/mqadv_dev914_linux_x86-64.tar.gz
container=oci
PWD=/
HOME=/root
SHLVL=1
BASE_TAG=8.1-279
MQ_PACKAGES=MQSeriesRuntime-*.rpm MQSeriesServer-*.rpm MQSeriesJava*.rpm MQSeriesJRE*.rpm MQSeriesGSKit*.rpm MQSeriesMsg*.rpm MQSeriesSamples*.rpm MQSeriesWeb*.rpm MQSeriesAMS-*.rpm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MQM_UID=888
BASE_IMAGE=registry.redhat.io/ubi8/ubi-minimal
_=/usr/bin/env
+ test -f /usr/bin/yum
+ YUM=false
+ test -f /usr/bin/microdnf
+ MICRODNF=true
+ test -f /usr/bin/rpm
+ RPM=true
+ test -f /usr/bin/apt-get
+ UBUNTU=false
+ false
+ true
+ EXTRA_RPMS='bash bc ca-certificates file findutils gawk glibc-common grep passwd procps-ng sed shadow-utils tar util-linux which'
+ false
+ true
+ microdnf install bash bc ca-certificates file findutils gawk glibc-common grep passwd procps-ng sed shadow-utils tar util-linux which

(process:12): librhsm-WARNING **: 17:10:00.438: Found 0 entitlement certificates

(process:12): librhsm-WARNING **: 17:10:00.445: Found 0 entitlement certificates

(process:12): libdnf-WARNING **: 17:10:00.446: Loading "/etc/dnf/dnf.conf": IniParser: Can't open file
Downloading metadata...
**error: cannot update repo 'ubi-8-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (28): Timeout was reached for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/repodata/repomd.xml [Connection timed out after 30001 milliseconds]
The command '/bin/sh -c env && chmod u+x /usr/local/bin/install-*.sh   && sleep 1   && install-mq-server-prereqs.sh $MQM_UID   && install-mq.sh $MQM_UID' returned a non-zero code: 1
make: *** [build-devserver] Error 1**

**Comment by arthurbarr** [comment]
I've not seen this error before.  This might be either a network error, or the CDN server may have been down.  I can access that same file without problem.

**Comment by fbsantana2020** [comment]
@arthurbarr ,

You were right. I ran on another network and it worked.

Thank you
