### ISSUE TITLE
Any way to change message format?

### ISSUE THREAD

**Issue by wjlewis** [ibm-messaging/mq-container#417]
Is there any way to change the message format? After I click `Create +`, I see a "Format" field, but it appears to be uneditable. Is there a way to change this?
<img width="502" alt="Screen Shot 2020-07-23 at 11 18 55 AM" src="https://user-images.githubusercontent.com/37314098/88304578-7965be00-ccd6-11ea-9868-033845d0c5bf.png">

**Comment by arthurbarr** [comment]
This repository is for issues and bugs specific to running MQ in containers, and not general MQ issues.  Can I suggest posting a question on stackoverflow.com, using the [ibm-mq](https://stackoverflow.com/questions/tagged/ibm-mq) tag?

**Comment by wjlewis** [comment]
Will do; thanks!
