### ISSUE TITLE
Is there any way to make two channels?

### ISSUE THREAD

**Issue by ctopCanada** [ibm-messaging/mq-container#422]
Is there any way to make two channels? and how to make inactive channel to running?

**Comment by arthurbarr** [comment]
You can have as many channels as you like.  You can define channels (and any other MQ objects) using a number of administrative interfaces, including the web console, [MQSC](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.2.0/com.ibm.mq.ref.adm.doc/q085520_.htm), and programmatically using PCF messages.

There are number of reasons for a channel to be marked as inactive, including:

- Channel has not been started (run `START CHANNEL` in MQSC)
- A client has not connected to the channel (`SVRCONN` channel)
- The channel has finished
- The channel has disconnected normally

See [CHSTATUS](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.2.0/com.ibm.mq.ref.adm.doc/q086090_.htm)

Please be advised that this repository is for issues specific to the samples provided for running MQ in containers.  General MQ questions are better submitted elsewhere, for example stackoverflow.com with the `ibm-mq` keyword.
