### ISSUE TITLE
MQ container build for version 9.0.0.8

### ISSUE THREAD

**Issue by GrimMinion** [ibm-messaging/mq-container#426]
Hi, I can't see a branch for version 9.0.0.
Please could anyone let me know if they have successfully created an MQ container image for 9.0.0.8? or know of a reason that this is not possible?

Branches available:
* 9.1.0                               
  9.1.3                               
  master                              
  remotes/origin/9.1.0                
  remotes/origin/9.1.0-sep            
  remotes/origin/9.1.1                
  remotes/origin/9.1.2                
  remotes/origin/9.1.2-UBI            
  remotes/origin/9.1.3                
  remotes/origin/9.1.4                
  remotes/origin/9.2.0                
  remotes/origin/HEAD -> origin/master
  remotes/origin/master

**Comment by arthurbarr** [comment]
This repository contains samples for MQ 9.1 onwards.  We do have an older (deprecated) repository for the older MQ 9.0 version: https://github.com/ibm-messaging/mq-docker/

MQ itself is supported in containers from MQ 8.0.0.4, so you just need to get it to run in a container.  We haven't tried the code in this repository on MQ 9.0.  Most of it should be OK, but you might find that some of the code relies on features which have been added into MQ to improve the container integration.
