### ISSUE TITLE
How do I connect to MQ server with JNDI properties. Where can I get jar file which has connectionFactory and jndi properties file.

### ISSUE THREAD

**Issue by svaranasi** [ibm-messaging/mq-container#430]

**Comment by arthurbarr** [comment]
The IBM MQ Knowledge Center has information on this, notably [Developing JMS and Java applications](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.2.0/com.ibm.mq.dev.doc/q118320_.htm), which includes sub-topics on accessing the files from Maven central (if you wish), and how you can use a JMS application in a Java EE server via a connectionFactory.

Please note that this repository is for issues specific to the sample container code for running an IBM MQ queue manager in containers.

**Comment by arthurbarr** [comment]
This sort of issue is better addressed on sites like stackoverflow.com, using the tag [ibm-mq](https://stackoverflow.com/questions/tagged/ibm-mq)
