### ISSUE TITLE
Error - Couldn't open file /var/downloads/IBM_MQ_9.2.0_LINUX_X86-64_NOINST.tar.gz

### ISSUE THREAD

**Issue by OmBabosa** [ibm-messaging/mq-container#431]
Hi,

We are trying to build a production image for MQ. i have downloaded the 'No-Install' MQ package (IBM_MQ_9.2.0_LINUX_X86-64_NOINST.tar.gz) for part no. CJ7CNML from Passport Advantage. 

i have also downloaded the GitHub code required to build this, specifically release v9.2.0. When downloaded this results in a root folder named 'mq-container-9.2.0'; created a 'downloads' directory inside 'mq-container-9.2.0' and copied the MQ package into the 'downloads' directory, and gave this a 777 permission, just to avoid any issue related to permission at a later stage.

Now, i run 'make build-advancedserver' from within the directory 'mq-container-9.2.0', but the image build seems to fail with below error:

STEP 8: RUN mkdir /opt/mqm   && chmod a+x /usr/local/bin/install-mq.sh   && sleep 1   && INSTALL_SDK=1 install-mq.sh   && chown -R 1001:root /opt/mqm/*
+ test -f /usr/bin/rpm
+ RPM=true
+ test -f /usr/bin/apt-get
+ UBUNTU=false
+ INSTALL_SDK=1
+ DIR_TMP=/tmp/mq
+ mkdir -p /tmp/mq
+ cd /tmp/mq
+ curl -LO file:///var/downloads/IBM_MQ_9.2.0_LINUX_X86-64_NOINST.tar.gz
curl: (37) Couldn't open file /var/downloads/IBM_MQ_9.2.0_LINUX_X86-64_NOINST.tar.gz
Error: error building at STEP "RUN mkdir /opt/mqm   && chmod a+x /usr/local/bin/install-mq.sh   && sleep 1   && INSTALL_SDK=1 install-mq.sh   && chown -R 1001:root /opt/mqm/*": error while running runtime: exit status 37
make: *** [build-advancedserver] Error 125

Could you please advise what i might be doing wrong; i think i just followed the steps provided. Am i missing anything?

Thanks in advance.

**Comment by arthurbarr** [comment]
Are you using Docker for Desktop on Windows by any chance?  There are often problems with bind-mounted volumes on Windows, as you're sharing a file from your Windows host into a Docker container.  I don't personally have a Windows machine to try this out on, but I think others have had success using Windows Subsystem for Linux and/or cygwin.

**Comment by OmBabosa** [comment]
I am using 'CentOS Linux 7'. Please let me know if you would need more details to help with the issue. Thanks for a quick response.

**Comment by OmBabosa** [comment]
The docker version seems to be very old on the machine, i am using this.

Docker version 1.13.1, build 64e9980/1.13.1

Do you think, this could be the issue? (i am planning to update it to latest and then try the image creation steps again)

**Comment by OmBabosa** [comment]
Hello again Arthru, apologies for the above; not meeting the required minimum version of docker. i removed the older version of docker and installed the latest, and the docker on the machine is now at 'Docker version 19.03.13, build 4484c46d9d'.

But, i still get the same error. Kindly advise.

**Comment by arthurbarr** [comment]
On Red Hat and CentOS systems, they've generally been moving away from docker towards `podman` instead.  If podman is installed, the MQ container build will use that instead, so you may find that works.  I've not seen the problem you've got, but I'll have a go and see if I can re-create the issue.

**Comment by OmBabosa** [comment]
Thanks Arthur. Yes, you are right - the machine has 'podman' installed, and the version is 'podman version 1.6.4'. Thank you for offering to look into it.

**Comment by KiranDarbha** [comment]
Could you try with following command

`MQ_ARCHIVE=<name of mqdriver in tar.gz form> make build-advancedserver`
**Please note** value of MQ_ARCHIVE must be set to name of the mq-driver present in your `mq-container-9.2.0/downloads` directory.

**Comment by arthurbarr** [comment]
I've tried this out on a CentOS 7 machine, and it worked fine as the root user, with the default file name (under the `downloads` directory):

```
-rw-r--r-- 1 root root 584341533 Nov  9 03:29 IBM_MQ_9.2.0_LINUX_X86-64_NOINST.tar.gz
```

As @KiranDarbha says, this could be a case of a file name mis-match.

**Comment by OmBabosa** [comment]
Thanks much Arthur and Kiran for your time on this and trying to help me. Just to clarify, i had originally tried by specifying MQ_ARCHIVE as well, and did take a note that file name matches, but had still got the error. Strange, as it runs for Arthur. But thanks for trying this out.

We have got access to licensed MQ images from the IBM container registry and hence, for now we are not required to build the MQ image on our own, and hence closing this issue for now. Thanks again !!

**Comment by ppintogbm** [comment]
Hi Everybody, 

Have the same problem today building on:
Fedora 31 - 5.8.18-100.fc31.x86_64
Podman - 2.1.1

In my case the solution was to modify the Makefile, to include :Z to the volume mount... get something like:
--volume $(DOWNLOADS_DIR):/var/downloads:Z

Probably is some SELinux related issue on RHEL based OS.
