### ISSUE TITLE
Set authority commands like setmqaut at object creation time

### ISSUE THREAD

**Issue by abinashkd** [ibm-messaging/mq-container#432]
I can create MQ objects and channels by placing the .mqsc file under /etc/mqm. 
Wondering how can I setup the authority on the MQ objects, like any place I can put the scripts for below command:

setmqaut -m QM1 -n QUEUE1 -t queue -p app +dsp +put +get

**Comment by lsabados** [comment]
Have you tried using the "SET AUTHREC..." command in your mqsc file?

**Comment by abinashkd** [comment]
@lsabados thank you for this valuable input. I was not aware of 'SET AUTHREC'. It worked like charm :)
