### ISSUE TITLE
How to disable MQ Advanced capabilities in production build

### ISSUE THREAD

**Issue by bony-cas** [ibm-messaging/mq-container#437]
We don't want to use any of the advanced capabilities at present. We built a production image of 9.2.1.0 using a modified install-mq.sh file - we altered the genmqpkg_incams variable from 1 to 0. The genmqpkg_incmqft and genmqpkg_incmqxr variables were already set to 0. When I started a container with this image and ran DIS QMGR ADVCAP it returned ADVCAP(ENABLED). I was expecting the parameter to show DISABLED. Can you advise the correct way to disable advanced capabilities. Thanks.

**Comment by callumpjackson** [comment]
Ideally the process that you have documented is what would be required, unfortunately it doesn't quite do everything needed. To complete the process you need to edit `Dockerfile-server` to remove a couple license files:

`RUN rm /opt/mqm/swidtag/ibm.com_IBM_MQ_Advanced-9.2.1.swidtag /opt/mqm/swidtag/IBM_MQ_Advanced-9.2.1.mqtag`

I verified this worked when I added this to line 107

**Comment by bony-cas** [comment]
This worked for me, thanks for the quick response.

**Comment by NeoScaler** [comment]
Thanks for pointing in the right direction, I nearly got mad that ADVCAP never got disabled, although all features were uninstalled. 

@bony-cas  We should not close this issue, it is definitely a bug resolving ADVCAP. According to the IBM documentation, if the features are not installed it should be DISABLED.
