### ISSUE TITLE
operator for handling queues and topics

### ISSUE THREAD

**Issue by davidkarlsen** [ibm-messaging/mq-container#449]
Disclaimer: this is the wrong repo for the ticket, but the k8s operator isn't public, so nowhere to register it.

It would be great if the operator: https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.ctr.doc/ctr_using_operator.htm could handle creation/parameters of queues and topics, and not only queue-managers.

This would make MQ truly user-friendly, as end-users could be self-serviced with queues via the k8s api.

**Comment by arthurbarr** [comment]
Hi @davidkarlsen .  I think you're right, that would be a great feature.  The best way to help get this prioritized is to raise an official Request for Enhancement (RFE).  The process is outlined [here](https://community.ibm.com/community/user/integration/viewdocument/reviewing-the-mq-rfe-request-for-e?CommunityKey=183ec850-4947-49c8-9a2e-8e7c7fc46c64&tab=librarydocuments).  This makes the feature request "official", and means it gets properly prioritized with other work.

As you say, this repo isn't the right place, as it's for the MQ sample image, so I propose you raise the RFE and that we close this issue.

**Comment by davidkarlsen** [comment]
that site doesn't respond, and issues reported there are usually just ignored.

**Comment by davidkarlsen** [comment]
It eventually responded and here is the RFE: https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=149603
