### ISSUE TITLE
Unable to Use REST Management Interface

### ISSUE THREAD

**Issue by sac80644** [ibm-messaging/mq-container#450]
Hello, I have been trying to implement some monitoring using the REST Management Interface (https://www.ibm.com/support/knowledgecenter/SS5K6E_9.1.0/com.ibm.mqa.doc/monitoring/mo00061_.htm) and have not been successful: GET https://localhost:9443/ibmmq/rest/mgmt

I keep getting:

{"error": [{
  "action": "Resubmit the request using a valid URI.",
  "completionCode": 0,
  "explanation": "There is no corresponding REST interface on the provided URI.",
  "message": "MQWB0116E: The URI cannot be invoked as it does not correspond to an existing REST interface.",
  "msgId": "MQWB0116E",
  "reasonCode": 0,
  "type": "rest"
}]}

**Comment by arthurbarr** [comment]
Try this:

```
% docker run -d -e LICENSE=accept --name qm1 -e MQ_QMGR_NAME=qm1 -p 9443:9443 -e MQ_ADMIN_PASSWORD=passw0rd ibmcom/mq
c0b0bc0ef56f59bbc306d1a3aa29493118ebc2b58acbfc2cfc6c055b88f4c8ee
```

Then wait a few seconds for it to start up, and try this:
```
% curl -k https://localhost:9443/ibmmq/rest/v2/admin/qmgr -X GET -u admin:passw0rd
{"qmgr": [{
  "name": "qm1",
  "state": "running"
}]}%                                                                                                                                                                        %
```

You can follow along with more detailed instructions in [Getting started with the administrative REST API](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.2.0/com.ibm.mq.adm.doc/q127600_.html), remembering to use the "admin" user provided with MQ Advanced for Developers, and the password you set.  If you don't want to use MQ Advanced for Developers, you'll need to set up your own users in the `mqwebuser.xml` file.
