### ISSUE TITLE
Docker file with MQClient

### ISSUE THREAD

**Issue by 2020testuser** [ibm-messaging/mq-container#457]
Hi,

Could anyone share the working version of Dockerfile with IBMMQClient and sample MQConnection program which can connect successfully to a remote MQ Server (which is not installed in the docker image) ? Appreciate any help!
Thanks in advance!

**Comment by arthurbarr** [comment]
We don't have a formal sample for the MQ clients, as the client is usually just a library in your application.  For example:

* The MQ Java clients are just a JAR file, and are available from Maven central, so are used just like any other JAR your app depends on (see ["Write and run your first IBM MQ JMS application"](https://developer.ibm.com/components/ibm-mq/tutorials/mq-develop-mq-jms/).
* The native clients (like C) are available in the "redistributable client package", which is just a TAR file.  So you'd just untar the file into your image, and then link the `.so` files into your application
 
It's very dependent on your application, programming language, and build tools.  See https://developer.ibm.com/components/ibm-mq/articles/mq-downloads for the actual clients for different languages.

The MQ samples are included in the redistributable client, for example `amqsputc` is a C sample to put a message over a client connection, and `amqsgetc` gets a message.  Which language are you interested in?

**Comment by 2020testuser** [comment]
@arthurbarr - I tried in both Go and Python language and got the same below error.
`MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_NOT_AUTHORIZED [2035]`
Could you point me to any link that has a sample Dockerfile with MQClient and language specific pakcage installed. I'm not sure from where it is taking mquser.

In the serverlog, I see the below error msg. 

`05/17/2021 11:41:43 AM - Process(91796.2121) User(mqm) Program(amqv)
                    Host(wmqrd0007.uhc.com) Installation(Installation1)
                    VRMF(9.1.0.3) QMgr(xxxx)
                    Time(2021-05-19T16:41:43.452Z)
                    ArithInsert1(2) ArithInsert2(2035)
                    CommentInsert1(mquser)
                    CommentInsert3(mquser)
AMQ9588E: Queue Manager User ID initialization failed for 'mquser'.
EXPLANATION:
The call to initialize the User ID 'mquser' failed with CompCode 2 and Reason
2035. If an MQCSP block was used, the User ID in the MQCSP block was ''. If a
userID flow was used, the User ID in the UID header was 'mquser' and any
CHLAUTH rules applied prior to user adoption were evaluated case-sensitively
against this value.
ACTION:
Correct the error and try again.`

**Comment by arthurbarr** [comment]
Ah, OK.  It sounds like the problem isn't so much getting the client going itself, but rather with MQ security.

The MQ server (queue manager) has authentication and authorization enabled by default, but has no users defined.  For MQ in containers, you typically need to connect your queue manager to an LDAP server to provide user information.

To make things easier, with the MQ Advanced for Developers container image, we've added two users for you out of the box: `app` and `admin`.  The `app` user is authorized to connect to the queue manager, and use any queue or topic beginning with "DEV.".  There are three queues pre-defined: `DEV.QUEUE.1`, `DEV.QUEUE.2` and `DEV.QUEUE.3`.  From your MQ client application, the `app` user does not need to supply a password by default, though you can choose to set a password on your queue manager container by setting the `MQ_APP_PASSWORD` environment variable.

**Comment by 2020testuser** [comment]
@arthurbarr - Thanks! Yes, it was a security issue. Got it working after setting right permissions for the userid in the Dockerfile.
