### ISSUE TITLE
MQ Appliance docker image?

### ISSUE THREAD

**Issue by jade2020** [ibm-messaging/mq-container#458]
Hi,

I'm not quite sure of the right place to ask about this. Out of curiosity, are there any plans to release a docker image of MQAppliance? I noticed that there is a docker image of DataPower Gateway and it got me intrigued if there are any plans for something similar for MQA.

Thanks,

**Comment by arthurbarr** [comment]
No, there are no plans for that.  Out of interest, which aspects of the MQ Appliance are you most interested in using in a container?  The MQ Operator for OpenShift offers a lot of power and flexibility.  If you looked at that, I'd be interested to know what the gap might be.

**Comment by jade2020** [comment]
Thanks for your response. I'm more interested in the config aspects of MQA. I  currently work with a client who do have some appliances and I was interested in getting access to an environment where I'm able to investigate/explore deeper to get a better understanding. I'd not heard of MQ Operator before -  l'll take a look.

Thanks
