### ISSUE TITLE
Putting big messages via the web UI

### ISSUE THREAD

**Issue by pascalbe-dev** [ibm-messaging/mq-container#459]
Hey, this might be a stupid question. However: How do I put bigger messages (> 1k chars) on a queue via the web ui?
It keeps cutting them at 1024 chars. 

I'm still using V 9.1.4.0 though. Is this issue still present with newer versions or is there a reason or a way to change the message content limit?

Thanks in advance for the help :)

**Comment by arthurbarr** [comment]
This is a known limitation, and is still present in the latest MQ release (9.2.2).

I'm going to close this issue, as it isn't specifically an issue for the MQ in containers sample, but rather a general MQ issue.

**Comment by pascalbe-dev** [comment]
Okay, thanks for the info.

**Comment by pascalbe-dev** [comment]
Is this a limitation to the web UI or the product itself? Do you know, if there is another way to put bigger messages there? Like via REST API calls or something like that. 
Sorry, I just can't find the documentation.

**Comment by arthurbarr** [comment]
The 1 KB limit is a web console restriction.  MQ itself can handle messages up to 100 MB in size, and also offers ways to segment even larger messages: https://www.ibm.com/docs/en/ibm-mq/9.2?topic=queue-handling-messages-greater-than-4-mb-long

MQ itself does provide REST APIs, but we don't pre-configure them in the container sample.  MQ also provides client libraries for a wide variety of languages.  See https://developer.ibm.com/articles/mq-downloads/

**Comment by pascalbe-dev** [comment]
Puh, okay. 
I would be interested in the reasoning behind this limitation :o 

I guess, I will then try to adjust the users and roles to being able to use the REST API. Seems like the admin user can not use the REST API and the app user can only write to DEV.* queues. 

Thanks for the quick responses by the way.

**Comment by arthurbarr** [comment]
You can add any additional authority records by adding additional `.mqsc` files under the `/etc/mqm` directory.  They'll then get applied at container start up.  So you can add permissions for additional queues and topics, for example, or define more queues.

The permissions for the REST API are controlled here: https://github.com/ibm-messaging/mq-container/blob/master/incubating/mqadvanced-server-dev/web/installations/Installation1/servers/mqweb/mqwebuser.xml  You can override this file in the image (under `/etc/mqm/web/installations/Installation1/servers/mqweb/`) with a new image layer, and then change it however you want.  The app/admin users are just a default configuration we apply to the MQ Advanced for Developers image, and there's lots of flexibility to configure it.
