### ISSUE TITLE
Configure the key repository via config or mounts

### ISSUE THREAD

**Issue by Trenthani** [ibm-messaging/mq-container#461]
I am building a OpenShift/kubernetes IBM MQ deployment and have found good detail on configuring much of what I need via deployment methods such as Helm, however I am looking for a way to configure the key repository for a QM dynamically at deploy time.  

My deployment doesn't call for the use of persistent storage therefore i am attempting to steer away from using init containers as i suspect these would be the next best option.

Is there a process to use the keys added to /etc/mqm/pki/keys/<QueueManagerName>/ and /etc/mqm/pki/trust/ to generate the key.kdb and such files in /var/mqm/qmgrs/<QueueManagerName>/ssl/ ??  The IBMCOM helm charts only seem to cater for added TLS for the console or http endpoints at 9443 but not for connections at say port 1414.

Keen for some assistance.  
Thanks

**Comment by arthurbarr** [comment]
This is exactly how the sample already works: keys added under `/etc/mqm/pki` are added to a KDB file at runtime.
