### ISSUE TITLE
How to provide custom MQ configuration

### ISSUE THREAD

**Issue by irl-segfault** [ibm-messaging/mq-container#471]
Hi all,

I don't want the default queue configs.  I want the image to start up with my own.  Is the best option here just to copy in a config file overwriting whatever's currently in /etc/mqm?  The only documentation relevant here mention the ENV var, but nothing about swapping the default queue config.  Any advice?

**Comment by arthurbarr** [comment]
If you mean the default developer configuration, you only get that if you are using the MQ Advanced for Developers image/sample.  For the regular production image, those aren't added at all (e.g. `make build-advancedserver` to build a production image, with no default configuration or security provider whatsoever — just the standard MQ defaults).

**Comment by irl-segfault** [comment]
thanks!
