### ISSUE TITLE
Error java Mac M1 

### ISSUE THREAD

**Issue by josefelipepc** [ibm-messaging/mq-container#480]
When creating and uploading the container

Error: Port Library failed to initialize: -1
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

This error apparently is for not support java version.

java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

**Comment by shabtu** [comment]
+1
Having the same issue with my M1 chip.

**Comment by arthurbarr** [comment]
Closing as duplicated of #476.  M1 is not supported.
