### ISSUE TITLE
DEV.QUEUE.4 and above are missing

### ISSUE THREAD

**Issue by Zordid** [ibm-messaging/mq-container#491]
According to https://www.ibm.com/docs/en/order-management?topic=toolkit-configuring-running-agents-in-containerized-developer there should be DEV.QUEUE.1 through 10 available out of the box...

But when I run the image (even the latest), only DEV.QUEUE.1 - 3 are present...

Why??

**Comment by arthurbarr** [comment]
This MQ sample has only ever had three `DEV` queues available.  Either that documentation is wrong, or it's referring to changes made in the IBM Sterling Order Management developer toolkit, which is not managed in this repository.  I'm afraid I don't know how you could raise issues on that toolkit.

**Comment by Zordid** [comment]
Ah ok... I was under the impression that those were referring to the same... :-(
I am using this image along with TestContainers to test some MQ functionality - and it is a great pain that I cannot (easily) create my own test queues - let alone only have 3 independent ones to play around with.

Would it be possible to allow creation of my own queues using environment variables during start of the container?

**Comment by arthurbarr** [comment]
I'm not sure it would make sense to create them using an environment variable, as there are lots of options to set when you create a queue.  The pre-configured queues are just for getting started.  You can create queues using a file, which you can drop into `/etc/mqm`, with a `.mqsc` extension.  For example:

```mqsc
DEFINE QLOCAL('DEV.QUEUE.4') REPLACE
DEFINE QLOCAL('DEV.QUEUE.5') REPLACE
DEFINE QLOCAL('DEV.QUEUE.6') REPLACE
DEFINE QLOCAL('DEV.QUEUE.7') REPLACE
DEFINE QLOCAL('DEV.QUEUE.8') REPLACE
DEFINE QLOCAL('DEV.QUEUE.9') REPLACE
DEFINE QLOCAL('DEV.QUEUE.10') REPLACE
```
