### ISSUE TITLE
unable to change the log size with in the pod

### ISSUE THREAD

**Issue by craigjolley** [ibm-messaging/mq-container#499]
Is there a way we can change the log size when the QM is created. currently creating 16 mb files.

**Comment by arthurbarr** [comment]
No there is not a way to do that without a code change.  Here's where you'd need to set it: https://github.com/ibm-messaging/mq-container/blob/4580cecf4973107dff184e8cbbcf9ac7f5b4e7df/cmd/runmqserver/qmgr.go#L210

**Comment by daniel-geiger-ibmde** [comment]
Would be really helpful to have an option to inject (generic) crtmqm args.

**Comment by arthurbarr** [comment]
This is now possible at queue manager creation time by setting the `MQ_QMGR_LOG_FILE_PAGES` variable, as documented in the [README](https://github.com/ibm-messaging/mq-container#environment-variables-supported-by-this-image).
