### ISSUE TITLE
MQ Web Console unable to login

### ISSUE THREAD

**Issue by ompraash** [ibm-messaging/mq-container#504]
Reading thru IBM [get started doc for Web](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=console-getting-started-web) 
Error on the login is `Login failed. Enter a valid user ID and password.`
URL : https://localhost:9443/ibmmq/console/login.html

Is there a different default credential?

Using docker image: icr.io/ibm-messaging/mq:9.2.5.0-r1

**Comment by ompraash** [comment]
Container is adjusted to use a different password as explained [here](https://github.com/ibm-messaging/mq-container/blob/master/docs/developer-config.md#web-console).

It would be nice if they matched to the base product offering.

**Comment by arthurbarr** [comment]
The base product offering doesn't set up security for you, so you wouldn't be able to log in at all, AFAIK.  Closing this issue, as you seem to have found the answer, but please feel free to re-open if you think there's still an issue here.
