### ISSUE TITLE
MQ web libraries not included when building production image

### ISSUE THREAD

**Issue by njjdn** [ibm-messaging/mq-container#513]
I followed the steps in https://github.com/ibm-messaging/mq-container/blob/master/docs/building.md to build a production MQ image. The resulting image, when ran as a container, does not include all necessary libraries to run MQ web. The tar file I used to build the image does contain all libraries. It looks like the makefile isn't copying all web libs into the image.
```
$ docker exec -ti qmdev bash
bash-4.4$ ls /opt/mqm/web/lib
bootstrap-agent.jar                       com.ibm.mq.rest.auth.osauth_1.0.0.jar           extract   fixes     versions
com.ibm.mq.rest.auth.basicauth_1.0.0.jar  com.ibm.mq.rest.utils.status.feature_1.0.0.jar  features  platform  ws-launch.jar
bash-4.4$ strmqweb

Error: Could not find or load main class com.ibm.ws.kernel.boot.cmdline.EnvCheck
```

**Comment by arthurbarr** [comment]
There are many more JAR files in that directory in my images.  I wonder if something went wrong during your build — do you see any errors?  Alternatively, it might be possible for your downloaded TAR file for MQ to have been corrupted.

I don't think this is a bug in the code, as we regularly build and test with the web server using this code.
