### ISSUE TITLE
Followup on closed issue #499: unable to change the log size with in the pod

### ISSUE THREAD

**Issue by christoph-weiss-ibm** [ibm-messaging/mq-container#526]
The closed issue https://github.com/ibm-messaging/mq-container/issues/499 introduced the new environment variable MQ_QMGR_LOG_FILE_PAGES.

However it looks like that this was only done on the master branch. 

Currently we use the 9.3.0 branch to build MQ custom image for the MQ LTS release (9.3.0.x).
Thus it would be great if you could merge the code also to this branch.

Thanks

**Comment by christoph-weiss-ibm** [comment]
@JEFFLUFC , @Alec-Painter : as I have seen that you have done recent changes on the 9.3.0 branch: 
Can you please take over my issue? 
Changes would be easy as only the changes from #499 needs to be merged to the 9.3.0 branch. 
And as pointed out above: I think this would help many IBMers and customers as 9.3.0 is still the official LTS branch.

**Comment by JEFFLUFC** [comment]
Hi @christoph-weiss-ibm, thanks for the message. We are aware that this request has been made to replicate these changes on the LTS branch and that it would benefit a number of IBMers and customers. Thank you

**Comment by christoph-weiss-ibm** [comment]
@JEFFLUFC  thanks for the feedback. Do you have any idea / intern plan when this will happen? 
I could also provide a pull request with the changes if that helps
