### ISSUE TITLE
RFE Review :Enhance of Log in JSON Format- Need to add Explanation section

### ISSUE THREAD

**Issue by vkrpatnaik** [ibm-messaging/mq-container#531]
Hi Team,

We need your help in fixing the logs in json format section.
In Json format section, the explanation section is missing
-------------------------------------------------------------
logs:
	format: basic
	debug : false
	
Logs written in general format.

17/11/2014 10:32:29 - Process(2132.1) User(USER_1) Program(runmqchi.exe)
Host(HOST_1) Installation(Installation1)
VRMF(8.0.0.0) QMgr (A.B.C)
AMQ9542: Queue manager is ending.

EXPLANATION:
The program will end because the queue manager is quiescing.
ACTION:
None.
--------------------------------------------------------------
--------------------------------------------------------------	
logs:
	format :  json
	debug  :  false

**Logs is written in JSON format** 
{
  "ibm_messageId":"AMQ9209E",
  "ibm_arithInsert1":0,
  "ibm_arithInsert2":0,
  "ibm_commentInsert1":"localhost (127.0.0.1)",
  "ibm_commentInsert2":"TCP/IP",
  "ibm_commentInsert3":"SYSTEM.DEF.SVRCONN",
  "ibm_datetime":"2018-02-22T06:54:53.942Z",
  "ibm_serverName":"QM1",
  "type":"mq_log",
  "host":"0df0ce19c711",
  "loglevel":"ERROR",
  "module":"amqccita.c:4214",
  "ibm_sequence":"1519282493_947814358",
  "ibm_remoteHost":"127.0.0.1",
  "ibm_qmgrId":"QM1_2018-02-13_10.49.57",
  "ibm_processId":4927,
  "ibm_threadId":4,
  "ibm_version":"9.0.5.0",
  "ibm_processName":"amqrmppa",
  "ibm_userName":"johndoe",
  "ibm_installationName":"Installation1",
  "ibm_installationDir":"/opt/mqm",
  "message":"AMQ9209E: Connection to host 'localhost (127.0.0.1)' for channel 'SYSTEM.DEF.SVRCONN' closed."
}

JSON formatted logs don't have Explanation section.

===========================================

**Expected Format in JSON format is** 

{
  "ibm_messageId":"AMQ9209E",
  "ibm_arithInsert1":0,
  "ibm_arithInsert2":0,
  "ibm_commentInsert1":"localhost (127.0.0.1)",
  "ibm_commentInsert2":"TCP/IP",
  "ibm_commentInsert3":"SYSTEM.DEF.SVRCONN",
  "ibm_datetime":"2018-02-22T06:54:53.942Z",
  "ibm_serverName":"QM1",
  "type":"mq_log",
  "host":"0df0ce19c711",
  "loglevel":"ERROR",
  "module":"amqccita.c:4214",
  "ibm_sequence":"1519282493_947814358",
  "ibm_remoteHost":"127.0.0.1",
  "ibm_qmgrId":"QM1_2018-02-13_10.49.57",
  "ibm_processId":4927,
  "ibm_threadId":4,
  "ibm_version":"9.0.5.0",
  "ibm_processName":"amqrmppa",
  "ibm_userName":"johndoe",
  "ibm_installationName":"Installation1",
  "ibm_installationDir":"/opt/mqm",
  "message":"AMQ9209E: Connection to host 'localhost (127.0.0.1)' for channel 'SYSTEM.DEF.SVRCONN' closed."
  "explanation":  We need the inclusion of Explanation in MQ Logs"
}

Please review and let us know if we can have this enhancement .

**Comment by arthurbarr** [comment]
The MQ container sample just forwards the standard JSON log produced by the MQ queue manager (e.g. `AMQERR01.json`).  This includes all the "inserts" into the longer log message, so you don't lose any information entirely, but it does mean you may need to look up the explanation in the docs.

I think the explanation is not included in order to keep the JSON logs smaller, and not cause huge log lines.  You could raise an official idea for a change in behaviour here: https://integration-development.ideas.ibm.com/ideas/new. This process allows others to vote on it, and gets it evaluated alongside other ideas.
