### ISSUE TITLE
JMSCMQ1049 - error Unmappable

### ISSUE THREAD

**Issue by cesarpir** [ibm-messaging/mq-container#544]
Hello, I need help or guidance, I have a listener who receives many messages, but I cannot handle one message, receive and view its content, this is the exception displayed in the pod:

The character set '1252(windows-1252) Unmappable Action: REPORT, Unmappable Replacement: 63, spaceByte: 32' cannot convert some or all of the string '[B@42c3bd63'

I'm using ibm.mq.jakarta version 9.3.4.0, Java 17, Spring Boot 3, please, if possible, any idea on how to receive or discard this message by my listener?
I tried adding additional configuration variables to my factory but with no positive results.
Something like:
-Dcom.ibm.mq.cfg.jmqi.UnmappableCharacterAction=REPLACE
-Dcom.ibm.mq.cfg.jmqi.UnmappableCharacterReplacement=63

Thanks

**Comment by arthurbarr** [comment]
I don't know the answer to your question, and it doesn't look like it's related specifically to MQ in containers, or the sample code in this repo.  Can I please suggest you either raise an IBM support ticket, or perhaps post somewhere like https://stackoverflow.com/questions/tagged/ibm-mq?

**Comment by cesarpir** [comment]
I understand, thank you for your attention, thank you
