### ISSUE TITLE
blocked from address '_gateway (172.17.0.1)' matched a record configured with USERSRC(NOACCESS)

### ISSUE THREAD

**Issue by jpmartins-ca** [ibm-messaging/mq-container#581]
Hello,

On a ARM64 macbook, I am trying to built an MQ_VERSION ?= 9.3.4.0 with `make build-devserver`

The image build and is on `docker image ls`, container starts, but it does not accepts connection to it. Seem to be failing to login, tried to figure out details in the logs, seems the channel is blocked...

The setup of container is with exposed port 1414 and
                    .withEnv("LICENSE", "accept")
                    .withEnv("MQ_QMGR_NAME", "QMGR")
                    .withEnv("MQ_APP_USER", "app")
                    .withEnv("MQ_APP_PASSWORD", "large-pass")

When i go and cat /mnt/mqm/data/qmgrs/QMGR/errors/AMQERR01.LOG

> ...
> ----- amqzmgr0.c : 3100 -------------------------------------------------------
> 09/19/2024 03:16:15 PM - Process(1542.1) User(mqm) Program(amqfqpub)
>                     Host(db22e0d2d05f) Installation(Installation1)
>                     VRMF(9.3.4.0) QMgr(QMGR)
>                     Time(2024-09-19T15:16:15.634Z)
>                     CommentInsert1(QMGR)
>                    
> AMQ5806I: Queued Publish/Subscribe Daemon started for queue manager QMGR.
> 
> EXPLANATION:
> Queued Publish/Subscribe Daemon started for queue manager QMGR.
> ACTION:
> None.
> ----- cmqxfcxc.c : 1428 -------------------------------------------------------
> 09/19/2024 03:16:16 PM - Process(1590.3) User(mqm) Program(amqrmppa)
>                     Host(db22e0d2d05f) Installation(Installation1)
>                     VRMF(9.3.4.0) QMgr(QMGR)
>                     Time(2024-09-19T15:16:16.259Z)
>                     RemoteHost(172.17.0.1)
>                     CommentInsert1(SYSTEM.DEF.SVRCONN)
>                     CommentInsert2(_gateway (172.17.0.1))
>                     CommentInsert3(CLNTUSER(app) ADDRESS(_gateway))
>                    
> AMQ9777E: Channel was blocked
> 
> EXPLANATION:
> The inbound channel 'SYSTEM.DEF.SVRCONN' was blocked from address '_gateway
> (172.17.0.1)' because the active values of the channel matched a record
> configured with USERSRC(NOACCESS). The active values of the channel were
> 'CLNTUSER(app) ADDRESS(_gateway)'.
> ACTION:
> Contact the systems administrator, who should examine the channel
> authentication records to ensure that the correct settings have been
> configured. The ALTER QMGR CHLAUTH switch is used to control whether channel
> authentication records are used. The command DISPLAY CHLAUTH can be used to
> query the channel authentication records.
> ----- cmqxrmsa.c : 1258 -------------------------------------------------------
> 09/19/2024 03:16:16 PM - Process(1590.3) User(mqm) Program(amqrmppa)
>                     Host(db22e0d2d05f) Installation(Installation1)
>                     VRMF(9.3.4.0) QMgr(QMGR)
>                     Time(2024-09-19T15:16:16.261Z)
>                     CommentInsert1(SYSTEM.DEF.SVRCONN)
>                     CommentInsert2(1590)
>                     CommentInsert3(172.17.0.1)
>                    
> AMQ9999E: Channel 'SYSTEM.DEF.SVRCONN' to host '172.17.0.1' ended abnormally.
> 
> EXPLANATION:
> The channel program running under process ID 1590 for channel
> 'SYSTEM.DEF.SVRCONN' ended abnormally. The host name is '172.17.0.1'; in some
> cases the host name cannot be determined and so is shown as '????'.
> ACTION:
> Look at previous error messages for the channel program in the error logs to
> determine the cause of the failure. Note that this message can be excluded
> completely or suppressed by tuning the "ExcludeMessage" or "SuppressMessage"
> attributes under the "QMErrorLog" stanza in qm.ini. Further information can be
> found in the System Administration Guide.
> ----- amqrmrsa.c : 628 --------------------------------------------------------
> 09/19/2024 03:16:44 PM - Process(1386.1) User(mqm) Program(amqzmuc0)
>                     Host(db22e0d2d05f) Installation(Installation1)
>                     VRMF(9.3.4.0) QMgr(QMGR)
>                     Time(2024-09-19T15:16:44.579Z)
>                     CommentInsert1(AUTOCONFIG)
>                    
> AMQ5041I: The queue manager task 'AUTOCONFIG' has ended.
> 
> EXPLANATION:
> The queue manager task AUTOCONFIG has ended.
> ACTION:
> None.
> ----- amqzmut0.c : 4067 -------------------------------------------------------

Also tried with different setup with similar response (Please check if the supplied username and password are correct on the queue manager to which you are connecting.  For further information, review the queue manager error logs and the Securing IBM MQ topic within IBM Knowledge Center.).

Other 2 setup attempted:
```
        ports:
            - 1414:1414
            - 14171:14171
            - 9443:9443
        environment:
            LANG: fr_FR.UTF-8
            LICENSE: accept
            MQ_QMGR_NAME: QMGR
            MQ_ADMIN_USER: admin
            MQ_ADMIN_PASSWORD: large-pass
            MQ_APP_USER: app
            MQ_APP_PASSWORD: large-pass
            MQ_DEV: false
            MQ_DISABLE_WEB_CONSOLE: false
```
also same result if start by
docker run \
  --env LICENSE=accept \
  --env MQ_QMGR_NAME=QMGR \  
  --publish 1414:1414 \
  --publish 9443:9443 \
  --detach \
  my-ibm-mq:9.3.4.0-arm64

Suspect something is wrong in my built image...

What am I doing wrong? Help?

**Comment by arthurbarr** [comment]
How are you trying to connect?  The MQ Advanced for Developers image includes a default developer configuration, but that uses `DEV.APP.SVRCONN` as the channel name for application messaging.

**Comment by jpmartins-ca** [comment]
Hello, I am using a junit test with the following code:
```
               ...
               MQQueueConnectionFactory mqQueueConnectionFactory = new MQQueueConnectionFactory();
                mqQueueConnectionFactory.setHostName(MQ_CONTAINER.getHost());
                mqQueueConnectionFactory.setPort(MQ_CONTAINER.getMappedPort(1414));
                mqQueueConnectionFactory.setTransportType(JMSC.MQJMS_TP_CLIENT_MQ_TCPIP);
                mqQueueConnectionFactory.setQueueManager("QMGR");

                MQQueueConnection connection = (MQQueueConnection) mqQueueConnectionFactory.createConnection("app", "large-pass"); // or with blank "" password for the case where i did no specify the MQ_ADMIN_PASSWORD env.

                Assertions.assertFalse(connection.isEmpty());
```
                
I am guessing this might be some sort of docker-desktop 4.23.0 for macbook issue, but without more specifics on the error cause it is hard to figure out. I have other containers, like and oracle database running normally. Also the console of ibmmq is accessible, but login is not working...

**Comment by jpmartins-ca** [comment]
> How are you trying to connect? The MQ Advanced for Developers image includes a default developer configuration, but that uses `DEV.APP.SVRCONN` as the channel name for application messaging.

Thank you arthurbarr. I tried to connect to DEV.APP.SVRCONN and it worked. Sorry I am a rookie on this MQ matters, and got a task on a legacy application to get it working on a new CPU architecture challenge on my hands (arm64 instead of x86_64).

Reviewed the project, and it seem there is a custom channel referenced inside a file being copied into /etc/mqm/mq_local.mqsc 

DEFINE chl(X_CHANNEL) CHLTYPE(SVRCONN) MCAUSER('admin') MAXINST(2000) maxinstc(300) descr('Connexion Applicative')

When I try that channel name instead of DEV.APP.SVRCONN the error in the container log is:
Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2540;AMQ9520: Channel not defined remotely. [3=X_CHANNEL]

I intent to keep working with it, any help will be most appreciated, have a nice Friday.

**Comment by jpmartins-ca** [comment]
Seems the issue might be related with this "The TCP/IP listener program could not bind to port number 1414. [ArithInsert1(1414), ArithInsert2(98), CommentInsert1(bind), CommentInsert2(TCP/IP)]"

on the /etc/mqm/mq_local.mqsc line:

DEFINE LISTENER('INSTANCE01LISTENER.TCP') TRPTYPE(TCP) PORT(1414) CONTROL(QMGR) descr('...')

**Comment by jpmartins-ca** [comment]
Apparently my create test container and do the test was not timed correctly and the queue was not ready yet to receive connections.

fixed it adding a wait for the message "AMQ5806I: Queued Publish/Subscribe Daemon started for queue manager QMGR. [CommentInsert1(QMGR)]"


await().atMost(15,SECONDS).until(()->MQ_CONTAINER.getLogs().contains("AMQ5806I"));
