### ISSUE TITLE
No zip available for 9.4.0.5 of IBM-MQ-Advanced-for-Developers-Non-Install-LinuxARM64.tar.gz

### ISSUE THREAD

**Issue by chughts** [ibm-messaging/mq-container#587]
The 9.4.0 branch in this repository is defaulting the version to 9.4.0.5 but there isn't a matching Non install package for Linux ARM64 on the download site at https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/

Workaround is the build the container with the command 

` MQ_VERSION=9.4.0.0 make build-devserver`

**Comment by arthurbarr** [comment]
An update to the Makefile has been pushed today, which reports this if the download fails, along with a list of available versions.
