### ISSUE TITLE
/var/mqm should be separated out into multiple volumes 

### ISSUE THREAD

**Issue by parrobe** [ibm-messaging/mq-container#62]
COPIED FROM https://github.com/ibm-messaging/mq-docker/issues/30

With a single mount point for /var/mqm the container cannot be run with an NFS volume because NFS cannot be used for MQ's shared memory files.

The MQ KnowledgeCenter recommends separating out /var/mqm/qmgrs, /var/mqm/log, /var/mqm/errors and /var/mqm/trace for performance reasons. This seems to make sense for container volumes as well so these should probably be the different volumes exposed by the MQ container.

mqs.ini should be moved at the same time, probably to /var/mqm/qmgrs, so it survives container restarts. Leaving it under /var/mqm would cause it to be lost, assuming the above volume changes are made. AMQ_MQS_INI_LOCATION can be set to make MQ's commands read from the new location.

**Comment by parrobe** [comment]
On further investigation it seems it might be necessary to mount /var/mqm as well as /var/mqm/[qmgrs|log|errors|trace] I'm not sure what the behaviour of Docker/Bluemix Containers/other is when you attempt to mount separate volumes to the same part of the file system? Might be worth closing this issue until we know more.

**Comment by magnus919** [comment]
Large WMQ customer here. I've got a business need for this one.

**Comment by magnus919** [comment]
(actually you're probably going to see a few people from my team all over this and other issues soon)

**Comment by arthurbarr** [comment]
Closing as this is solved.  You can mount files into `/mnt/mqm`, `/mnt/mqm-log` and `/mnt/mqm-data`.  The `mqs.ini` wasn't moved over, but it still works.
