### ISSUE TITLE
We need a smarter way of checking return codes from MQSC scripts

### ISSUE THREAD

**Issue by parrobe** [ibm-messaging/mq-container#63]
COPIED FROM https://github.com/ibm-messaging/mq-docker/issues/47

Currently we use `set +e` to turn off script error checking before we run all of the MQSC scripts the user has supplied. Once that has finished we turn script error checking back on using `set -e`.

This isn't ideal as it means that serious errors with people's scripts (such as syntax errors) do not get picked up and could cause confusion such as `where is that object i tried to create?`. We had to add it in because on multiple starts the `START LISTENER(<LISTENER>)` command (where the <LISTENER> was created with `CONTROL(QMGR)` fails with the `listener is already active` error. (which isn't really an error)

What we need is some way to check the error codes returned by MQSC and error out if a serious error happens and continue if a warning style error happens

**Comment by arthurbarr** [comment]
This has now been fixed with an MQ product update.  If an MQSC command includes the IGNSTATE parameter, then `runmqsc` won't give an error code if it's already in that state.  This allows us to always enable error checking on the `runmqsc` call.
