### ISSUE TITLE
v9.0.5: unable to connect through app channel

### ISSUE THREAD

**Issue by m1schka** [ibm-messaging/mq-container#70]
Hey.

since version 9.0.5 I'm unable to connect through the dev app channel. I saw some changes in that area (no `app` mca configured anymore) but even after trying to manually add the `app` as mca to the channel (as before) I still can't connect.

 I'm using [the still kind of alpha jms package](https://github.com/ibm-messaging/mq-jms-spring). In the logs of the container, I see it's trying to authenticate my local OSX user from outside the docker container, which is obviously not authorizable. 
```
The inbound channel 'DEV.APP.SVRCONN' was blocked from address '172.19.0.1'
because the active values of the channel were mapped to a userid which should
be blocked. The active values of the channel were 'MCAUSER(app)
CLNTUSER(michael)'.
```

My workaround is using the admin user with password which feels kind of wrong. I'm still new to IBM MQ, with the permission system tricky to understand IMO.

Any help is appreciated!

**Comment by parrobe** [comment]
Hi @m1schka ,

Can we confirm the image you are running. I've tried to recreate your problem with the developer image and i can connect an application to my `DEV.APP.SVRCONN` channel which has the `app` user set in the `MCAUSER` field on start.

**Are you building this locally or are you using the `ibmcom/mq` dockerhub image?**

If you're building this locally you need to make sure that you run `make build-devserver` and this will produce two images:

- mqadvanced-server-dev-base
- mqadvanced-server-dev

`mqadvanced-server-dev` is the image you want to run as this contains the default configuration that allows your applications to connect. `mqadvanced-server-dev-base` does not contain this configuration.

> I'm still new to IBM MQ, with the permission system tricky to understand IMO.
We appreciate the feedback, MQ Security is a topic we know to be confusing and tricky to understand for new users. We're currently working on improving the security setup and also provide more educational resources for new users. Hopefully these will help new users understand MQ securiyt once they're done.
As a new user a great place to go find resources to help learn MQ is the [IBM MQ developer works site.](https://developer.ibm.com/messaging/ibm-mq/)

**Comment by m1schka** [comment]
I pulled the latest docker container and the problem is gone. not sure what caused the issue in the first place but who knows. Thx
